# -*- python -*-
# 2009, Copyright University Corporation for Atmospheric Research

import eol_scons
from SCons.Script import Environment

env = Environment(tools=['default', 'nidas'])

env.Program('client', "client.cc")
