# -*- python -*-
#
Import('env')
env = env.Clone(tools = ['nidas'])

env.Append(LIBS = env.NidasLibs())
env.Append(LIBS = ['boost_unit_test_framework', 'boost_regex'])
env.Prepend(CPPPATH = [ '#/src' ])
env.Append(CCFLAGS = ['-Wall'])

tests = env.Program('tiostream', "tiostream.cc")
# env.Depends(tests, libs)

# Add --log_level=all to see all the log messages
runtest = env.Command("xtest", tests, ["$SOURCE.abspath"])
env.Precious(runtest)
AlwaysBuild(runtest)
Alias('test', runtest)



