# -*- python -*-
# 2009, Copyright University Corporation for Atmospheric Research
#

from SCons.Script import Environment

env = Environment(tools=['default', 'nidasapps', 'valgrind', 'boost_test',
                         'boost_regex'])

tests = env.Program('tiostream', "tiostream.cc")

# Add --log_level=all to see all the log messages
runtest = env.Command("xtest", tests, ["$SOURCE.abspath"])
env.Precious(runtest)
env.AlwaysBuild(runtest)
env.Alias('test', runtest)
