# -*- python -*-

from SCons.Script import Environment

env = Environment(tools=['default', 'nidasapps', 'valgrind', 'boost_test'])

tests = env.Program('ttrh', ["ttrh.cc"])

env.AppendENVPath('LD_LIBRARY_PATH', '/opt/nc_server/lib')
runtest = env.Command("xtest", tests,
                      env.ChdirActions(["./$SOURCE.file"]))
env.Precious(runtest)
env.AlwaysBuild(runtest)
env.Alias('test', runtest)

env.ValgrindLog('memcheck',
                env.Command('vg.memcheck.log', tests,
                            "cd ${SOURCE.dir} && "
                            "${VALGRIND_PATH} --leak-check=full"
                            " --gen-suppressions=all ./${SOURCE.file}"
                            " >& ${TARGET.abspath}"))
