from SCons.Script import Split, SConscript, Alias

# Testing targets, built and run only on host

dirs = Split("""
iterators
serial_sensor
tlogger
core
data_dump
tiostream
network
nidsmerge
sync_server_dump
ck_xml
ck_calfile
UTime
sonic
prep
dausensor
trh
gps
wind2d
""")

SConscript(dirs=dirs)

slowdirs = Split("""serial_sensor sync_server_dump""")

qdirs = [d for d in dirs if d not in slowdirs]
Alias('qtest', qdirs)
