
# Testing targets, built and run only on host

dirs = Split("""
autoconfig
iterators
serial_sensor
tlogger
core
data_dump
tiostream
network
sync_server_dump
ck_xml
ck_calfile
UTime
sonic
prep
dausensor
trh
gps""")

Import('env')
SConscript(dirs=dirs, exports='env')
