
# Testing targets, built and run only on host

dirs = Split("""
autoconfig
iterators
serial_sensor
tlogger
core
hardware
util
tiostream
network
sync_server_dump
ck_xml
ck_calfile
UTime
trh
gps""")
# sonic
# data_dump
# dausensor
# prep

Import('env')
SConscript(dirs=dirs, exports='env')
