#! /bin/sh
#
#
# Aircraft Data System
#
# . /etc/default/rcS

# set -x

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=dsm
NAME=dsm
DESC="dsm"

ruser=ads
server=192.168.184.1
adspath=/home/local/hiaper/ads3

modpath=/var/tmp/modules
libpath=/var/tmp/lib
dsmpath=/var/tmp

modconf=/etc/dsm_modules.conf

if [ ! -r $modconf ]; then
    echo "$modconf not found"
    exit 1
fi

# check if a module is loaded, if not insmod it
insmod_chk() {
	lsmod | fgrep -q $1 || insmod "$@"
}

# check if a module is loaded, if so rmmod it
rmmod_chk() {
	lsmod | fgrep -q $1 && rmmod $1
}

# return an array of module names:
#    the first word of each non-comment line in stdin
get_modules() {
    while read module rest_of_line; do

        # echo "${modline[*]}"

        echo "$module" | egrep -q "^ *$" && continue
        echo "$module" | egrep -q "^ *#" && continue
        echo "$module"
    done
}

# load the modules read from stdin. This can't use
# get_modules because it needs the whole line
load_modules() {
    depmod
    while read -a modline; do
        echo "${modline[0]}" | egrep -q "^ *$" && continue
        echo "${modline[0]}" | egrep -q "^ *#" && continue
        insmod_chk "${modline[@]}"
    done
}

unload_modules() {
    # use tac (reverse cat) to read stdin backwards since we
    # want to unload the modules in the reverse order
    # modules=($(tac -| get_modules))
    # for m in ${modules[*]}; do
    #     rmmod_chk $m
    # done

    # unfortunately tac doesn't exist in busybox on embedded systems
    # so we'll go through the array backwards.
    modules=($(get_modules))
    for (( i=${#modules[*]}-1; i >= 0; i-- )); do
        rmmod_chk ${modules[$i]}
    done
}


#
# Connect to the NTP time server
#
# /usr/sbin/ntpdate server && hwclock --systonc

copy_modules() {
    [ -d $modpath ] || mkdir -p $modpath
    modules=($(get_modules))
    for m in ${modules[*]}; do
        [ $m == rtl ] && continue	# don't fetcth rtl.o
	scp $ruser@$server:$adspath/dsm/modules/arm/$m.o $modpath
    done
}
copy_apps() {
        [ -d $libpath ] || mkdir -p $libpath
        [ -d $dsmpath/filters ] || mkdir -p $dsmpath/filters
        
	scp $ruser@$server:$adspath/dsm/class/arm/libDsm.so $libpath
	scp $ruser@$server:$adspath/dsm/src/arm/dsm $dsmpath
	scp $ruser@$server:$adspath/dsm/filters/*.cfg $dsmpath/filters
}

start_app() {
        cd $dsmpath
	# start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
	# 	-b --exec $DAEMON
	./dsm -d > /var/log/dsm.log 2>&1 &
}

stop_app() {
        # cd $dsmpath
	# start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid \
 	# 	--exec $DAEMON
 	echo "sending HUP to dsm"
 	pkill -HUP dsm
 	i=0
 	while [ $i -lt 5 ]; do
	 	sleep 2
	 	pgrep dsm || break
		i=$((i+1))
 	done
 	if [ $i == 5 ]; then
	 	echo "doing kill -9"
	 	pkill -9 dsm
	fi
}

case "$1" in
  start)
	echo -n "Starting $DESC (fetch & load modules, fetch app, run dsm): "
	unload_modules < $modconf
        copy_modules < $modconf
        load_modules < $modconf
        copy_apps
        start_app
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC and unloading modules: "
	stop_app
        # unload_modules < $modconf
	echo "$NAME."
	;;
  restart)
	echo -n "Restart of $DESC (does not unload modules or fetch app): "
	stop_app
	sleep 1
	start_app
	echo "$NAME."
	;;
  unload)
	echo -n "Unload of $DESC (unloads modules): "
	stop_app
	unload_modules < $modconf
	;;
  reload)
	echo -n "Reload of $DESC (reloads modules and restarts dsm): "
	stop_app
	unload_modules < $modconf
	load_modules < $modconf
	start_app
	  ;;
  refetch)
	echo -n "Refetch of $DESC (stops dsm, fetches app, starts dsm): "
        stop_app
        copy_apps
	start_app
  ;;
  refetch_all)
	echo -n "Refetch_all of $DESC (stops dsm, unloads mods, fetches all, starts dsm): "
        stop_app
	unload_modules < $modconf
	copy_modules < $modconf
	load_modules < $modconf
        copy_apps
	start_app
  ;;
  *)
	N=/etc/init.d/$NAME
	# echo "Usage: $N {start|stop|restart|reload|refetch|refetch_all}" >&2
	echo "Usage: $N {start|stop|restart|reload|refetch|refetch_all}" >&2
	exit 1
	;;
esac

exit 0

