# -*- python -*-
##  Copyright 2005,2006 UCAR, NCAR, All Rights Reserved

Import('env')
arch = env['ARCH']  # empty string for native builds

sources = Split("""
    ATIK_Sonic.cc
    CSAT3_Sonic.cc
    CS_Krypton.cc
    CSI_CRX_Binary.cc
    CSI_IRGA_Sonic.cc
    GroundStation.cc
    MOSMote.cc
    NetcdfRPCChannel.cc
    NetcdfRPCOutput.cc
    PropVane.cc
    RebsLinear.cc
    SonicAnemometer.cc
    WisardMote.cc
""")

headers = Split("""
    ATIK_Sonic.h
    CSAT3_Sonic.h
    CS_Krypton.h
    CSI_CRX_Binary.h
    CSI_IRGA_Sonic.h
    GroundStation.h
    MOSMote.h
    NetcdfRPCChannel.h
    NetcdfRPCOutput.h
    PropVane.h
    RebsLinear.h
    SonicAnemometer.h
    WisardMote.h
""")

env.Append (LIBNIDAS_DYNLD_SOURCES = [ env.File(f) for f in sources ])

if arch == '':
    env.Install('$PREFIX/include/nidas/dynld/isff', headers)

