# -*- python -*-

##  Copyright 2005 UCAR, NCAR, All Rights Reserved

import glob
import fnmatch
import os
import localutils


##
##  Import the cross-build environment.
##
Import('env')
# env = env.Clone()
arch = env['ARCH']

# -ggdb
# -DXML_DEBUG
# env.AppendUnique(CXXFLAGS = Split("""
# """))

def write_version_cc(env,target,source):
    """
    Write Version.cc file containing the contents of source.
    """
    out = open(target[0].path, "w")
    out.write('#include <nidas/core/Version.h>\n')
    out.write('const char* nidas::core::Version::version="' +
    	source[0].get_contents() + '";\n')
    out.close()

env.Command("Version.cc",[Value(localutils.get_svnversion(env))],write_version_cc)

env.CXXFile(target='AsciiSscanf.cc',source='AsciiSscanf.ll')

##
##  List of headers files
##
# headers = glob.glob("../../util/*.h")
# print(["glob headers="] + [str(h) for h in headers])
headers = Split("""
    AdaptiveDespiker.h
    AsciiSscanf.h
    CalFile.h
    CharacterSensor.h
    ConnectionInfo.h
    ConnectionRequester.h
    Datagrams.h
    DatagramSocket.h
    DerivedDataClient.h
    DerivedDataReader.h
    DOMable.h
    DOMObjectFactory.h
    DSMCatalog.h
    DSMConfig.h
    DSMEngine.h
    DSMEngineIntf.h
    DSMSensor.h
    DSMServer.h
    DSMServerApp.h
    DSMServerIntf.h
    DSMService.h
    DSMTime.h
    DynamicLoader.h
    FileSet.h
    FsMount.h
    HeaderSource.h
    IOChannel.h
    IODevice.h
    IOStream.h
    LooperClient.h
    Looper.h
    McSocket.h
    McSocketUDP.h
    MultipleUDPSockets.h
    NearestResampler.h
    NearestResamplerAtRate.h
    NidsIterators.h
    Parameter.h
    PhysConstants.h
    PortSelectorTest.h
    Project.h
    ProjectConfigs.h
    Prompt.h
    RemoteSerialConnection.h
    RemoteSerialListener.h
    Resampler.h
    RTL_DevIoctl.h
    RTL_DevIoctlStore.h
    RTL_IODevice.h
    SampleAverager.h
    SampleClient.h
    SampleClientList.h
    SampleClock.h
    Sample.h
    SampleInput.h
    SampleInputHeader.h
    SampleIOProcessor.h
    SampleLengthException.h
    SampleOutput.h
    SampleOutputRequestThread.h
    SampleParseException.h
    SamplePipeline.h
    SamplePool.h
    SampleBuffer.h
    SampleScanner.h
    SampleSorter.h
    SampleSource.h
    SampleSourceSupport.h
    SampleTag.h
    SampleThread.h
    SensorCatalog.h
    SensorHandler.h
    SensorOpener.h
    ServiceCatalog.h
    Site.h
    Socket.h
    SocketAddrs.h
    SocketIODevice.h
    TCPSocketIODevice.h
    UDPSocketIODevice.h
    ServerSocketIODevice.h
    SortedSampleSet.h
    StatusHandler.h
    StatusListener.h
    StatusThread.h
    TestSampleClient.h
    UnixIOChannel.h
    UnixIODevice.h
    Variable.h
    VariableConverter.h
    Version.h
    XDOM.h
    XMLConfigInput.h
    XMLConfigWriter.h
    XMLException.h
    XMLFdBinInputStream.h
    XMLFdFormatTarget.h
    XMLFdInputSource.h
    XMLParser.h
    XMLWriter.h
    XmlRpcThread.h
    XMLStringConverter.h
""")

# print(["headers="] + [str(h) for h in headers])

sources = Split("""
    AdaptiveDespiker.cc
    AsciiSscanf.cc
    CalFile.cc
    CharacterSensor.cc
    DatagramSocket.cc
    DerivedDataReader.cc
    DOMable.cc
    DOMObjectFactory.cc
    DSMCatalog.cc
    DSMConfig.cc
    DSMEngine.cc
    DSMEngineIntf.cc
    DSMSensor.cc
    DSMServer.cc
    DSMServerApp.cc
    DSMServerIntf.cc
    DSMService.cc
    DSMTime.cc
    FileSet.cc
    FsMount.cc
    HeaderSource.cc
    IOChannel.cc
    IOStream.cc
    Looper.cc
    McSocket.cc
    McSocketUDP.cc
    MultipleUDPSockets.cc
    NearestResampler.cc
    NearestResamplerAtRate.cc
    NidsIterators.cc
    Parameter.cc
    PortSelectorTest.cc
    Project.cc
    ProjectConfigs.cc
    RemoteSerialConnection.cc
    RemoteSerialListener.cc
    RTL_DevIoctl.cc
    RTL_DevIoctlStore.cc
    RTL_IODevice.cc
    SampleAverager.cc
    Sample.cc
    SampleClientList.cc
    SampleClock.cc
    SampleInputHeader.cc
    SampleIOProcessor.cc
    SampleOutput.cc
    SampleOutputRequestThread.cc
    SamplePipeline.cc
    SamplePool.cc
    SampleBuffer.cc
    SampleScanner.cc
    SampleSorter.cc
    SampleSourceSupport.cc
    SampleTag.cc
    SensorCatalog.cc
    SensorHandler.cc
    SensorOpener.cc
    ServiceCatalog.cc
    Site.cc
    Socket.cc
    SocketIODevice.cc
    TCPSocketIODevice.cc
    UDPSocketIODevice.cc
    ServerSocketIODevice.cc
    StatusHandler.cc
    StatusListener.cc
    StatusThread.cc
    TestSampleClient.cc
    Variable.cc
    VariableConverter.cc
    Version.cc
    XMLConfigWriter.cc
    XMLException.cc
    XMLFdFormatTarget.cc
    XMLParser.cc
    XMLWriter.cc
    XmlRpcThread.cc
""")

# r"xxx" is a raw string, escape sequences are left alone
dynlddef = r"NIDAS_DYNLD_LIBRARY_PATH=\"$PREFIX/lib\""

# dyn_sources = [ sources, env.SharedObject("DynamicLoader.cc", CPPDEFINES=dynlddef) ]
dyn_objs = [ env.SharedObject(sources), env.SharedObject("DynamicLoader.cc", CPPDEFINES=dynlddef) ]

##
##  Build the libnidas library. Search other needed libraries.
##
# Note that the addition of "build_util" to LIBPATH actually causes the
# addition of FOUR -L options to the linker commands.  It appears scons
# parses the name in multiple places, recognizes it as a build directory,
# then adds a -L argument for every combination of build and source
# directories with build_core in it.  Maybe it's a bug in scons, or some
# deep mystery.  Anyway, this is avoided by putting a directory node for
# build_core in the path instead of a string.
lib = env.SharedLibrary('nidas' , dyn_objs,
    LIBS= ['nidas_util','dl','xerces-c','xmlrpcpp'] + env['LIBS'],
    LIBPATH = [env.Dir('../build_util')] + env['LIBPATH'])

##
## Install targets for libraries and headers.
##
installed_lib = env.Install('$PREFIX/lib',lib)
env.Install('$PREFIX/include/nidas/core',headers)

# print [ env.subst('$PREFIX/lib/') + os.path.basename(File(l).path) for l in lib]

# env.Clean(arch + '_install', [
#     ('$PREFIX/lib/' + os.path.basename(File(l).path) for l in lib)
#     ])
env.Clean('install', [
    ('$PREFIX/lib/' + os.path.basename(File(l).path) for l in lib)
    ])


env['LIBNIDAS'] = lib[0]
