# -*- python -*-

##  Copyright 2005,2006 UCAR, NCAR, All Rights Reserved

##
##  Import the build environment.
##
Import(['env'])
arch = env['ARCH']  # empty string for native builds

# The Makefile must be listed in the source dependencies
# so that it is copied/linked to the variant_dir.
# The Kmake builder runs the make command in variant_dir.
#
# Also, the SConscript command that invokes this SConscript
# file should set duplicate=1, so that all the linux module
# source files, including the Makefile, are copied to the variant_dir.
# so that make can find them and do its work outside of the
# source tree.

headers = Split("""
""")

if (env.has_key("LINUX_MODULES") and
    env.has_key('KERNELDIR') and env['KERNELDIR'] != ''):

    modules = ['mesa.ko']
    env.Kmake(modules, headers + ['mesa.c', 'Makefile'])

    env.Install('$LINUX_MODULES', modules)

    env.Clean('install',[
        '$LINUX_MODULES/' + l for l in modules
        ])

# Some kernel module header files define symbols that are needed
# by user code. These must also be installed in $PREFIX/include
shared_headers = Split("""
""")

if arch == '':
    env.Install('$PREFIX/include/nidas/linux/mesa', shared_headers)
