
Import('env')
env = env.Copy()

env.Append (LIBS = ['boost_unit_test_framework', 'boost_regex', 'nidas_util'],
            CPPPATH = [ "#", "#/nidas/util" ],
            LIBPATH = [ "#/build_x86/build_util" ],
            RPATH = [ env.Dir("#/build_x86/build_util").abspath ])
tests = env.Program('tlogger', "tlogger.cc")

runtest = env.Command("xtest", tests, ["$SOURCE.abspath"])
env.Precious(runtest)
AlwaysBuild(runtest)
Alias('test', runtest)

