# -*- python -*-

Import('env')
env = env.Clone()

libs = [ env['LIBNIDAS_DYNLD'], env['LIBNIDAS'], env['LIBNIDAS_UTIL'] ]
env.Append(LIBS = libs[0])
env.Append (LIBS = ['boost_unit_test_framework', 'boost_regex'],
            CPPPATH = [ "#", "#/nidas/util" ])
tests = env.Program('tlogger', "tlogger.cc")
env.Depends(tests, libs)

runtest = env.Command("xtest", tests, ["$SOURCE.abspath"])
env.Precious(runtest)
AlwaysBuild(runtest)
Alias('test', runtest)

