# -*- python -*-

##  Copyright 2005 UCAR, NCAR, All Rights Reserved

import glob
import fnmatch
import os

##
##  Import the cross-build environment.
##
Import('env')
# env = env.Clone()
arch = env['ARCH']

# -ggdb
# -DXML_DEBUG
# env.AppendUnique(CXXFLAGS = Split("""
# """))

SConscript(dirs = ["raf", "isff", "iss"], exports={'env':env})

headers = [ Split("""
    A2DSensor.h
    AsciiOutput.h
    DSC_A2DSensor.h
    DSC_AnalogOut.h
    DSC_FreqCounter.h
    DSC_PulseCounter.h
    DSMSerialSensor.h
    FileSet.h
    FsMount.h
    GPS_NMEA_Serial.h
    ParoSci_202BG_Calibration.h
    ParoSci_202BG_P.h
    ParoSci_202BG_T.h
    RawSampleInputStream.h
    RawSampleOutputStream.h
    RawSampleService.h
    SampleArchiver.h
    SampleInputStream.h
    SampleOutputStream.h
    StatisticsCruncher.h
    StatisticsProcessor.h
    TSI_CPC3772.h
    ViperDIO.h
    XMLConfigService.h
""") ]

##
##  source files in libnidas_dynld
##
sources = [ Split("""
    A2DSensor.cc
    AsciiOutput.cc
    DSC_A2DSensor.cc
    DSC_AnalogOut.cc
    DSC_FreqCounter.cc
    DSC_PulseCounter.cc
    DSMSerialSensor.cc
    FileSet.cc
    FsMount.cc
    GPS_NMEA_Serial.cc
    ParoSci_202BG_Calibration.cc
    ParoSci_202BG_P.cc
    ParoSci_202BG_T.cc
    RawSampleInputStream.cc
    RawSampleOutputStream.cc
    RawSampleService.cc
    SampleArchiver.cc
    SampleInputStream.cc
    SampleOutputStream.cc
    StatisticsCruncher.cc
    StatisticsProcessor.cc
    TSI_CPC3772.cc
    ViperDIO.cc
    XMLConfigService.cc
""") ]

if arch == 'arm':
    archsources=Split("""
    """)
    archheaders=Split("""
    """)
else:
    archsources=Split("""
    """)
    archheaders=Split("""
    """)

SConscript(dirs="psql", duplicate=0, exports={'env':env})

##
##  Build the nidas_dynld library.
##
env.Append (LIBNIDAS_DYNLD_SOURCES = sources + archsources )
lib = env.SharedLibrary('nidas_dynld' , env['LIBNIDAS_DYNLD_SOURCES'],
    LIBS=['nidas','dl'] + env['LIBS'],
    LIBPATH = [env.Dir('../build_core')] + env['LIBPATH'])

##
## Install targets for library and headers.
##
env.Install('$PREFIX/lib',lib)
env.Install('$PREFIX/include/nidas/dynld',headers + archheaders)

# print [ env.subst('$PREFIX/lib/') + os.path.basename(File(l).path) for l in lib]

env.Clean(arch + '_install', [
    ('$PREFIX/lib/' + os.path.basename(File(l).path) for l in lib)
    ])
