FROM library/centos:7
LABEL organization="NCAR EOL"

RUN rpm -ihv http://www.eol.ucar.edu/software/rpms/eol-repo-epel-1-3.noarch.rpm

# xmlrpc++ contains /usr/lib64/pkgconfig/xmlrpcpp.pc, which the
# scons tool wants to find.

# ael-base creates symbolic links with the i686 version of /lib/ld-linux
# so that the old arcom binaries work, so install glibc.i686 before nidas-ael
# nidas-ael requires ael-base, but if ael-base isn't specified explicitly
# it seems the latest version is not fetched. Not sure why. So list
# ael-base explicitly.

# eol_scons will be mounted into the container, so it does not need to be
# installed.  epel-release is required to install scons as python2-scons
# package.

RUN yum install -y epel-release
RUN yum install -y scons git flex glibc.i686 nidas-ael ael-base

# install some i686 stuff needed by old /opt/arcom/bin binaries.
# The intent is to make this command run without failing due to
# missing library dependencies:
# PATH=$PATH:/opt/arcom/bin; LD_LIBRARY_PATH=/usr/lib fakeroot /opt/arcom/bin/dpkg
# RUN yum install -y fakeroot-libs.i686 zlib.i686

# If we need fakeroot and dnf can't find the i686 version:
# RUN rpm -ihv --nodeps --force /tmp/docker-files/fakeroot-1.20.2-4.fc24.i686.rpm

WORKDIR /root

