# -*- python -*-

##  Copyright 2005,2006 UCAR, NCAR, All Rights Reserved

##
##  Import the build environment.
##
Import('env')

# The Makefile must be listed in the source dependencies
# so that it is copied/linked to the build_dir.
# The Kmake builder runs the make command in build_dir.
#
# Also, the SConscript command that invokes this SConscript
# file should set duplicate=1, so that all the linux module
# source files, including the Makefile, are copied to the build_dir.
# so that make can find them and do its work outside of the
# source tree.

arinc_files = Split("""
    Makefile
    main.c
    arinc.h
    CEI420A/Source/api220.c
    CEI420A/Source/api220.h
    CEI420A/Source/apiutils.c
    CEI420A/Source/arincx20.h
    CEI420A/Source/lowlevel.h
    CEI420A/Source/fpga420a_16mhz_v100.h
    CEI420A/Source/i960_220.h
    CEI420A/Include/utildefs.h
""")

env.Kmake('arinc.ko',arinc_files)

if env.has_key('KERNELDIR') and env['KERNELDIR'] != '':
    env.Install('$PREFIX/linux','arinc.ko')

# Some kernel module header files define symbols that are needed
# by user code. These must also be installed in $PREFIX/include
headers = Split("""
    arinc.h
""")

env.Install('$PREFIX/include/nidas/linux/arinc',headers)
