# -*- python -*-
# 2009-2024, Copyright University Corporation for Atmospheric Research

from SCons.Script import Environment

env = Environment(tools=['default', 'nidasapps'])

nidsmerge = env.NidasApp('nidsmerge')
data_stats = env.NidasApp('data_stats')
data_dump = env.NidasApp('data_dump')
sensor_extract = env.NidasApp('sensor_extract')

depends = ["test_nidsmerge.sh", nidsmerge, data_stats,
           data_dump, sensor_extract]
runtest = env.Command("xtest", depends,
                      ["cd $SOURCE.dir && ./test_nidsmerge.sh"])

env.Precious(runtest)
env.AlwaysBuild(runtest)
env.Alias('test', runtest)
