# -*- python -*-

##
##  Import the cross-build environment.
##
Import('arm_env')
rtl_env = arm_env.Copy()

##
##  RTLinux specific settings
##
rtl_env.AppendUnique(CCFLAGS=Split("""
  -fno-common -msoft-float -DMODULE -D_LOOSE_KERNEL_NAMES
  -D__KERNEL__ -D__LINUX_ARM_ARCH__=5 -D__RTL__
"""))
rtl_env.AppendUnique(CPPPATH=Split("""
  /opt/rtldk-2.0/rtlinuxpro/include
  /opt/rtldk-2.0/rtlinuxpro/include/linux-sys
  /opt/rtldk-2.0/rtlinuxpro/include/compat
  /opt/rtldk-2.0/rtlinuxpro/libc/include
  /opt/rtldk-2.0/rtlinuxpro/linux/include
  /opt/rtldk-2.0/rtlinuxpro/include/posix
"""))
##
##  List of each module source
##
modules = Split("""
  rtl_com8_driver.c
  init_modules.c
  isa_serial.c
  isa_demux.c
  irig_module.c
""")

##
##  Build the modules
##
for i in modules:
  rtl_env.Object( i )
