# -*- python -*-

##  Copyright 2005 UCAR, NCAR, All Rights Reserved

##
##  Import the cross-build environment.
##

Import('env')
myenv = env.Copy()

##
##  RTLinux specific settings
##
myenv.Replace(CC = '/opt/rtldk-2.2/bin/arm-linux-gcc')

myenv.AppendUnique(CCFLAGS=Split("""
  -DMODULE -D__RTCORE_KERNEL__
  -nostdinc
  -isystem /opt/rtldk-2.2/bin/../lib/gcc-lib/arm-linux/3.3.2/include/  
"""))

#    -Wa,-mcpu=xscale -mapcs -mapcs-32 -march=armv4 -mno-sched-prolog
#    -mshort-load-bytes -mtune=strongarm -Uarm -DDSM
#    -fno-omit-frame-pointer -fno-strict-aliasing

myenv.AppendUnique(CPPPATH=Split("""
  /opt/rtldk-2.2/rtlinuxpro/include/app/rtl
  /opt/rtldk-2.2/rtlinuxpro/linux/include
  /opt/rtldk-2.2/rtlinuxpro/include
  #dsm/modules/CEI420A/Include
  #dsm/modules/CEI420A/Source
"""))

##
##  List of each module source
##
# main.c  -> ioctl_fifo.c + xxxx_driver.c
# irig.c  -> pc104sg.c
# demux.c -> rtl_isa_irq.c
# vdio.c
modules = Split("""
    dsm_serial.c
    dsm_serial_fifo.c
    rtl_isa_irq.c
    pc104sg.c
    ioctl_fifo.c
    xxxx_driver.c
    arinc.c
""")

##
##  Build the modules
##
for i in modules:
  myenv.Object( i )
