# -*- python -*-
#
Import('env')
env = env.Clone()

libs = [ env['LIBNIDAS_DYNLD'], env['LIBNIDAS'], env['LIBNIDAS_UTIL'] ]
env.Append(LIBS = libs[0])
env.Append(CPPPATH = [ "#", "#/nidas" ])
env.Append(CCFLAGS = ['-Wall'])

env.Depends(env.Program('sensor_sim.cc'), libs)
