# env = Environment(CCFLAGS='-Wall')

Program('sensor_sim.cc',
    LIBS=['nidas_dynld','nidas'],LIBPATH='/opt/local/nidas/x86/lib',
    CCFLAGS='-Wall',CPPPATH='/opt/local/nidas/x86/include',RPATH='/opt/local/nidas/x86/lib'
)
