# -*- python -*-
## 2007, Copyright University Corporation for Atmospheric Research

from SCons.Script import Environment, Import

##
##  Import the build environment.
##
Import(['env'])

env: Environment

headers = env.Split("usbtwod.h")

env.NidasKernelModule(
    ['usbtwod.ko'],
    ['usbtwod.c','usbtwod.h','Makefile'] +
    env.SymbolModules('revinfo', 'util'),
    headers)
