# -*- python -*-
## 2007, Copyright University Corporation for Atmospheric Research

from SCons.Script import Environment, Import

##
##  Import the build environment.
##
Import(['env'])

env: Environment

headers = env.Split("pcmcom8.h")

env.NidasKernelModule(
    ['pcmcom8.ko'],
    ['pcmcom8.c', *env.SymbolModules('revinfo')],
    headers)

env.InstallModuleConf('pcmcom8.conf')
env.InstallEtcDefaults('pcmcom8', 'pcmcom8.defaults')
