# -*- python -*-

##  Copyright 2006 UCAR, NCAR, All Rights Reserved

Import('env')
arch = env['ARCH']
env = env.Clone(CPPDEFINES = 'DEBUG', LIBS=[], SHLIBPREFIX = '')

libtilt = env.SharedLibrary3("nidas_dynld_iss_TiltSensor",
                             "TiltSensor.cc")
                             
libwicor = env.SharedLibrary3("nidas_dynld_iss_WICORSensor",
                              "WICORSensor.cc")

headers = Split("""TiltSensor.h WICORSensor.h""")

instlibs = []
instlibs.extend(env.SharedLibrary3Install('$PREFIX', libtilt))
instlibs.extend(env.SharedLibrary3Install('$PREFIX', libwicor))

# env.Clean(arch + '_install',[
#     (('$PREFIX/lib/' + os.path.basename(File(l).path)) for l in so)
#     ])
env.Clean('install',instlibs)

env.Install('$PREFIX/include/nidas/dynld/iss', headers)

