# -*- python -*-

##  Copyright 2006 UCAR, NCAR, All Rights Reserved

Import('env')
arch = env['ARCH']

so = []

so.extend(env.SharedLibrary3("nidas_dynld_iss_TiltSensor",
                             "TiltSensor.cc",
                             CPPDEFINES = 'DEBUG',
                             SHLIBPREFIX = '',LIBS=[]))

so.extend(env.SharedLibrary3("nidas_dynld_iss_WICORSensor",
                             "WICORSensor.cc",
                             CPPDEFINES = 'DEBUG',
                             SHLIBPREFIX = '',LIBS=[]))

headers = Split("""TiltSensor.h WICORSensor.h""")

instlibs = env.SharedLibrary3Install('$PREFIX', so)

# env.Clean(arch + '_install',[
#     (('$PREFIX/lib/' + os.path.basename(File(l).path)) for l in so)
#     ])
env.Clean('install',instlibs)

env.Install('$PREFIX/include/nidas/dynld/iss', headers)

