# -*- python -*-
## 2006, Copyright University Corporation for Atmospheric Research


Import('env')
arch = env['ARCH']  # empty string for native builds

sources = Split("""TiltSensor.cc WICORSensor.cc""")
headers = Split("""TiltSensor.h WICORSensor.h""")

if False:
    env = env.Clone(CPPDEFINES = 'DEBUG', LIBS=[], SHLIBPREFIX = '')

    libtilt = env.SharedLibrary3("nidas_dynld_iss_TiltSensor",
                                 "TiltSensor.cc")

    libwicor = env.SharedLibrary3("nidas_dynld_iss_WICORSensor",
                                  "WICORSensor.cc")

    instlibs = []
    instlibs.extend(env.SharedLibrary3Install('$ARCHPREFIX', libtilt))
    instlibs.extend(env.SharedLibrary3Install('$ARCHPREFIX', libwicor))

    env.Clean('install', instlibs)

env.Append (LIBNIDAS_DYNLD_SOURCES = [ env.File(f) for f in sources ])

env.Install('$ARCHPREFIX/include/nidas/dynld/iss', headers)
