version: 2.1
executors:
  armhf-executor:
    docker:
      - image: docker.io/ncar/nidas-build-debian-armhf:jessie_v1

  armel-executor:
    docker:
      - image: docker.io/ncar/nidas-build-debian-armel:jessie_v1

  buster-armhf-executor:
    docker:
      - image: docker.io/ncar/nidas-build-debian-armhf:buster_v1

commands:
  clone-source:
    description: "Clone the source tree"
    parameters:
      branch:
        type: enum
        enum: [master, autoconfig, buster]
        default: buster
    steps:
      - run:
          name: Clone GitHub repository
          command: git clone -b << parameters.branch >> --single-branch https://github.com/ncareol/nidas
  
  build:
    description: "Build nidas with arch parameter"
    parameters:
      arch:
        type: string
        default: "host"
    steps:
      - run:
          name: Build NIDAS for << parameters.arch >>
          command: |
            cd nidas/src
            scons LINUX_MODULES=no BUILDS=<< parameters.arch >>

  test:
    description: "Native Build of nidas then test"
    steps:
#      - build
      - run:
          name: NIDAS Native Build and Unit Test
          command: |
            cd nidas/src
            scons LINUX_MODULES=no tests

  build-pkgs:
    description: "Build packages associated arch: armhf, armel"
    parameters:
      arch:
        type: string
        default: armhf
    steps:
      - run:
          name: NIDAS Package Build for arch parameter
          command: | 
            pushd nidas/scripts
            ./build_dpkg.sh  << parameters.arch >>
            popd
            ls -alg
            mkdir pkgs && cp *.deb pkgs
            ls -alg pkgs

  deploy-pkgs:
    description: "Deploy packages to packagecloud.io"
    steps:
      - deploy:
          name: Upload all packages to debian:jessie packagecloud.io
          command: |
             package_cloud push ncareol/isfs/raspbian/jessie ./pkgs/nidas*_arm??.deb

jobs:
  build-armhf-master:
    executor: armhf-executor
    working_directory: .
    steps:
      - clone-source:
          branch: master
      - build:
          arch: armhf

  test-armhf-master:
    executor: armhf-executor
    working_directory: .
    steps:
      - clone-source:
          branch: master
      - test

  package-armhf-master:
    executor: armhf-executor
    working_directory: .
    steps:
      - clone-source:
          branch: master
      - build-pkgs:
          arch: armhf
      - persist_to_workspace:
          root: .
          paths: 
            - pkgs

  deploy-armhf-master:
    executor: armhf-executor
    working_directory: .
    environment:
      PACKAGECLOUD_TOKEN: 06ddd11da1ae900dccd755ce1acd48ee6ab9f62e2d930318
    steps:
      - attach_workspace:
          at: .
      - deploy-pkgs
  
  build-armel-master:
    executor: armel-executor
    working_directory: .
    steps:
      - clone-source:
          branch: master
      - build

  test-armel-master:
    executor: armel-executor
    working_directory: .
    steps:
      - clone-source:
          branch: master
      - test

  package-armel-master:
    executor: armel-executor
    working_directory: .
    steps:
      - clone-source:
          branch: master
      - build-pkgs:
          arch: armel
      - persist_to_workspace:
          root: .
          paths: 
            - pkgs

  deploy-armel-master:
    executor: armel-executor
    working_directory: .
    environment:
      PACKAGECLOUD_TOKEN: 06ddd11da1ae900dccd755ce1acd48ee6ab9f62e2d930318
    steps:
      - attach_workspace:
          at: .
      - deploy-pkgs
  
  build-armhf-autoconfig:
    executor: armhf-executor
    working_directory: .
    steps:
      - clone-source:
          branch: autoconfig
      - build:
          arch: armhf

  test-armhf-autoconfig:
    executor: armhf-executor
    working_directory: .
    steps:
      - clone-source:
          branch: autoconfig
      - test

  package-armhf-autoconfig:
    executor: armhf-executor
    working_directory: .
    steps:
      - clone-source:
          branch: autoconfig
      - build-pkgs:
          arch: armhf
      - persist_to_workspace:
          root: .
          paths: 
            - pkgs

  deploy-armhf-autoconfig:
    executor: armhf-executor
    environment:
      PACKAGECLOUD_TOKEN: 06ddd11da1ae900dccd755ce1acd48ee6ab9f62e2d930318
    working_directory: .
    steps:
      - attach_workspace:
          at: .
      - deploy-pkgs

  build-armhf-buster:
    executor: buster-armhf-executor
    working_directory: .
    steps:
      - clone-source:
          branch: buster
      - build:
          arch: armhf

  test-armhf-buster:
    executor: buster-armhf-executor
    working_directory: .
    steps:
      - clone-source:
          branch: buster
      - test

  package-armhf-buster:
    executor: buster-armhf-executor
    working_directory: .
    steps:
      - clone-source:
          branch: buster
      - build-pkgs:
          arch: armhf
      - persist_to_workspace:
          root: .
          paths: 
            - pkgs

  deploy-armhf-buster:
    executor: buster-armhf-executor
    environment:
      PACKAGECLOUD_TOKEN: 06ddd11da1ae900dccd755ce1acd48ee6ab9f62e2d930318
    working_directory: .
    steps:
      - attach_workspace:
          at: .
      - deploy-pkgs

  build-armel-autoconfig:
    executor: armel-executor
    working_directory: .
    steps:
      - clone-source:
          branch: autoconfig
      - build:
          arch: armel

  test-armel-autoconfig:
    executor: armel-executor
    working_directory: .
    steps:
      - clone-source:
          branch: autoconfig
      - test 

  package-armel-autoconfig:
    executor: armel-executor
    working_directory: .
    steps:
      - clone-source:
          branch: autoconfig
      - build-pkgs:
          arch: armel
      - persist_to_workspace:
          root: .
          paths: 
            - pkgs
    
  deploy-armel-autoconfig:
    executor: armel-executor
    working_directory: .
    environment:
      PACKAGECLOUD_TOKEN: 06ddd11da1ae900dccd755ce1acd48ee6ab9f62e2d930318
    steps:
      - attach_workspace:
          at: .
      - deploy-pkgs

workflows:
  version: 2
  master-armhf:
    jobs:
      - build-armhf-master:
          filters:
            branches:
              only: 
                - master
      - test-armhf-master:
          filters:
            branches:
              only: 
                - master
      - package-armhf-master:
          # requires:
          #   - test-armhf-master
          filters:
            branches:
              only: 
                - master
      - deploy-armhf-master:
          # requires:
          #   - package-armhf-master
          filters:
            branches:
              only: 
                - master
      
  # master-armel:
  #   jobs:
      # - build-armel-master:
      #     filters:
      #       branches:
      #         only: 
      #           - master
      # - test-armel-master:
      #     filters:
      #       branches:
      #         only: 
      #           - master
      # - package-armel-master:
      #   #  requires:
      #   #    - test-armel-master
      #     filters:
      #       branches:
      #         only: 
      #           - master
      # - deploy-armel-master:
      #     # requires:
      #     #   - package-armel-master
      #     filters:
      #       branches:
      #         only: 
      #           - master

#  autoconfig-armhf:
#    jobs:
#      # - build-armhf-autoconfig:
#      #     filters:
#      #       branches:
#      #         only: 
#      #           - auto-config
#      - test-armhf-autoconfig:
#          filters:
#            branches:
#              only: 
#                - auto-config
#      - package-armhf-autoconfig:
#          requires:
#            - test-armhf-autoconfig
#          filters:
#            branches:
#              only: 
#                - auto-config
#      - deploy-armhf-autoconfig:
#          requires:
#            - package-armhf-autoconfig
#          filters:
#            branches:
#              only: 
#                - auto-config
      
  buster-armhf:
    jobs:
      # test job does the build. no need to do it twice
      # - build-armhf-buster:
      #     filters:
      #       branches:
      #         only: 
      #           - buster
      - test-armhf-buster:
          filters:
            branches:
              only: 
                - buster
      - package-armhf-buster:
          requires:
            - test-armhf-buster
          filters:
            branches:
              only: 
                - buster
      - deploy-armhf-buster:
          requires:
            - package-armhf-buster
          filters:
            branches:
              only: 
                - buster
      
#  autoconfig-armel:
#    jobs:
#      # - build-armel-autoconfig:
#      #     filters:
#      #       branches:
#      #         only: 
#      #           - auto-config
#      - test-armel-autoconfig:
#          filters:
#            branches:
#              only: 
#                - auto-config
#      - package-armel-autoconfig:
#          requires:
#            - test-armel-autoconfig
#          filters:
#            branches:
#              only: 
#                - auto-config
#      - deploy-armel-autoconfig:
#          requires:
#            - package-armel-autoconfig
#          filters:
#            branches:
#              only: 
#                - auto-config
