version: 2.1
executors:
  armhf-executor:
    docker:
      - image: docker.io/ncar/nidas-build-debian-armhf:jessie_v1

  armel-executor:
    docker:
      - image: docker.io/ncar/nidas-build-debian-armel:jessie_v1
 
jobs:
  build-armhf-master:
    executor: armhf-executor
    working_directory: .
    steps:
      - run:
          name: Clone GitHub repository
          command: git clone -b ${CIRCLE_BRANCH} --single-branch https://github.com/ncareol/nidas
      - run:
          name: NIDAS Build of Master Branch for RPi/armhf
          command: |
            cd nidas/src
            scons LINUX_MODULES=no BUILDS=armhf

  test-armhf-master:
    executor: armhf-executor
    working_directory: .
    steps:
      - run:
          name: Clone GitHub repository
          command: git clone -b ${CIRCLE_BRANCH} --single-branch https://github.com/ncareol/nidas
      - run:
          name: NIDAS Native Build and Test of Master Branch
          command: |
            cd nidas/src
            scons LINUX_MODULES=no
            scons LINUX_MODULES=no tests

  package-armhf-master:
    executor: armhf-executor
    working_directory: .
    steps:
      - run:
          name: Clone GitHub repository
          command: git clone -b ${CIRCLE_BRANCH} --single-branch https://github.com/ncareol/nidas
      - run:
          name: NIDAS Package Build of Master Branch for RPi/armhf
          command: | 
            pushd nidas/scripts
            ./build_dpkg.sh armhf
            popd
            mkdir pkgs && cp *.deb pkgs
      - persist_to_workspace:
          root: .
          paths: pkgs

  deploy-armhf-master:
    executor: armhf-executor
    working_directory: .
    environment:
      PACKAGECLOUD_TOKEN: 06ddd11da1ae900dccd755ce1acd48ee6ab9f62e2d930318
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install packagecloud CLI
          command: gem install package_cloud
      - deploy:
          name: Upload RPi2 armhf package to debian:armhf packagecloud.io
          command: |
             package_cloud push ncareol/isfs/raspbian/jessie ./pkgs/nidas-rpi2_*_armhf.deb
      - deploy:
          name: Upload armhf package to debian:armhf packagecloud.io
          command: |
             package_cloud push ncareol/isfs/raspbian/jessie ./pkgs/nidas_*_armhf.deb
  
  build-armel-master:
    executor: armel-executor
    working_directory: .
    steps:
      - run:
          name: Clone GitHub repository
          command: git clone -b ${CIRCLE_BRANCH} --single-branch https://github.com/ncareol/nidas
      - run:
          name: NIDAS Build of Master Branch for PC104/armel
          command: |
            cd nidas/src
            scons LINUX_MODULES=no BUILDS=armel

  test-armel-master:
    executor: armel-executor
    working_directory: .
    steps:
      - run:
          name: Clone GitHub repository
          command: git clone -b ${CIRCLE_BRANCH} --single-branch https://github.com/ncareol/nidas
      - run:
          name: NIDAS Native Build and Test of Master Branch
          command: |
            cd nidas/src
            scons LINUX_MODULES=no
            scons LINUX_MODULES=no tests

  package-armel-master:
    executor: armel-executor
    working_directory: .
    steps:
      - run:
          name: Clone GitHub repository
          command: git clone -b ${CIRCLE_BRANCH} --single-branch https://github.com/ncareol/nidas
      - run:
          name: NIDAS Package Build of Master Branch for PC104/armel
          command: | 
            pushd nidas/scripts
            ./build_dpkg.sh armel
            popd
            mkdir pkgs && cp *.deb pkgs
      - persist_to_workspace:
          root: .
          paths: pkgs

  deploy-armel-master:
    executor: armel-executor
    working_directory: .
    environment:
      PACKAGECLOUD_TOKEN: 06ddd11da1ae900dccd755ce1acd48ee6ab9f62e2d930318
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install packagecloud CLI
          command: gem install package_cloud
      - deploy:
          name: Upload PC104 armel package to debian:armel packagecloud.io
          command: |
             package_cloud push ncareol/isfs/raspbian/jessie ./pkgs/nidas-rpi2_*_armel.deb
      - deploy:
          name: Upload nidas armel package to debian:armel packagecloud.io
          command: |
             package_cloud push ncareol/isfs/raspbian/jessie ./pkgs/nidas_*_armel.deb
  
  build-armhf-autoconfig:
    executor: armhf-executor
    working_directory: .
    steps:
      - run:
          name: Clone GitHub repository
          command: git clone -b ${CIRCLE_BRANCH} --single-branch https://github.com/ncareol/nidas
      - run:
          name: NIDAS Build of AutoConfig Branch for RPi/armhf
          command: | 
            cd nidas/src
            scons LINUX_MODULES=no BUILDS=armhf

  test-armhf-autoconfig:
    executor: armhf-executor
    working_directory: .
    steps:
      - run:
          name: Debug user permissions
          command: whoami && groups `whoami` && echo $PWD && ls -alg
      - run:
          name: Clone GitHub repository
          command: git clone -b ${CIRCLE_BRANCH} --single-branch https://github.com/ncareol/nidas
      - run:
          name: NIDAS Native Build and Test of Autoconfig Branch
          command: |
            cd nidas/src
            scons LINUX_MODULES=no
            scons LINUX_MODULES=no tests

  package-armhf-autoconfig:
    executor: armhf-executor
    working_directory: .
    steps:
      - run:
          name: Clone GitHub repository
          command: git clone -b ${CIRCLE_BRANCH} --single-branch https://github.com/ncareol/nidas
      - run:
          name: NIDAS Package Build of AutoConfig Branch for RPi/armhf
          command: | 
            pushd nidas/scripts
            ./build_dpkg.sh armhf
            popd
            mkdir pkgs && cp *.deb pkgs
      - persist_to_workspace:
          root: .
          paths: pkgs

  deploy-armhf-autoconfig:
    executor: armhf-executor
    environment:
      PACKAGECLOUD_TOKEN: 06ddd11da1ae900dccd755ce1acd48ee6ab9f62e2d930318
    working_directory: .
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install packagecloud CLI
          command: gem install package_cloud
      - deploy:
          name: Upload RPi2 armhf package to debian:armhf packagecloud.io
          command: |
             package_cloud push ncareol/isfs/raspbian/jessie ./pkgs/nidas-rpi2_*_armhf.deb
      - deploy:
          name: Upload armhf package to debian:armhf packagecloud.io
          command: |
             package_cloud push ncareol/isfs/raspbian/jessie ./pkgs/nidas_*_armhf.deb

  build-armel-autoconfig:
    executor: armel-executor
    working_directory: .
    steps:
      - run:
          name: Clone GitHub repository
          command: git clone -b ${CIRCLE_BRANCH} --single-branch https://github.com/ncareol/nidas
      - run:
          name: NIDAS Build of AutoConfig Branch for PC104/armel
          command: | 
            cd nidas/src
            scons LINUX_MODULES=no BUILDS=armel

  test-armel-autoconfig:
    executor: armel-executor
    working_directory: .
    steps:
      - run:
          name: Debug user permissions
          command: whoami && groups `whoami` && echo $PWD && ls -alg
      - run:
          name: Clone GitHub repository
          command: git clone -b ${CIRCLE_BRANCH} --single-branch https://github.com/ncareol/nidas
      - run:
          name: NIDAS Native Build and Test of Autoconfig Branch
          command: |
            cd nidas/src
            scons LINUX_MODULES=no
            scons LINUX_MODULES=no tests

  package-armel-autoconfig:
    executor: armel-executor
    working_directory: .
    steps:
      - run:
          name: Clone GitHub repository
          command: git clone -b ${CIRCLE_BRANCH} --single-branch https://github.com/ncareol/nidas
      - run:
          name: NIDAS Package Build of AutoConfig Branch for PC104/armel
          command: | 
            pushd nidas/scripts
            ./build_dpkg.sh armel
            popd
            mkdir pkgs && cp *.deb pkgs
      - persist_to_workspace:
          root: .
          paths: pkgs
    
  deploy-armel-autoconfig:
    executor: armel-executor
    working_directory: .
    environment:
      PACKAGECLOUD_TOKEN: 06ddd11da1ae900dccd755ce1acd48ee6ab9f62e2d930318
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install packagecloud CLI
          command: gem install package_cloud
      - deploy:
          name: Upload PC104 armel package to debian:armel packagecloud.io
          command: |
             package_cloud push ncareol/isfs/raspbian/jessie ./pkgs/nidas-rpi2_*_armel.deb
      - deploy:
          name: Upload nidas armel package to debian:armel packagecloud.io
          command: |
             package_cloud push ncareol/isfs/raspbian/jessie ./pkgs/nidas_*_armel.deb

workflows:
  version: 2
  # master-armhf:
  #   jobs:
      # - build-armhf-master:
      #     filters:
      #       branches:
      #         only: 
      #           - master
      # - test-armhf-master:
      #     filters:
      #       branches:
      #         only: 
      #           - master
      # - package-armhf-master:
      #     # requires:
      #     #   - test-armhf-master
      #     filters:
      #       branches:
      #         only: 
      #           - master
      # - deploy-armhf-master:
      #     # requires:
      #     #   - package-armhf-master
      #     filters:
      #       branches:
      #         only: 
      #           - master
      
  # master-armel:
  #   jobs:
      # - build-armel-master:
      #     filters:
      #       branches:
      #         only: 
      #           - master
      # - test-armel-master:
      #     filters:
      #       branches:
      #         only: 
      #           - master
      # - package-armel-master:
      #   #  requires:
      #   #    - test-armel-master
      #     filters:
      #       branches:
      #         only: 
      #           - master
      # - deploy-armel-master:
      #     # requires:
      #     #   - package-armel-master
      #     filters:
      #       branches:
      #         only: 
      #           - master

  autoconfig-armhf:
    jobs:
      # - build-armhf-autoconfig:
      #     filters:
      #       branches:
      #         only: 
      #           - auto-config
      - test-armhf-autoconfig:
          filters:
            branches:
              only: 
                - auto-config
      - package-armhf-autoconfig:
          requires:
            - test-armhf-autoconfig
          filters:
            branches:
              only: 
                - auto-config
      - deploy-armhf-autoconfig:
          requires:
            - package-armhf-autoconfig
          filters:
            branches:
              only: 
                - master
      
  autoconfig-armel:
    jobs:
      # - build-armel-autoconfig:
      #     filters:
      #       branches:
      #         only: 
      #           - auto-config
      - test-armel-autoconfig:
          filters:
            branches:
              only: 
                - auto-config
      - package-armel-autoconfig:
          requires:
            - test-armel-autoconfig
          filters:
            branches:
              only: 
                - auto-config
      - deploy-armel-autoconfig:
          requires:
            - package-armel-autoconfig
          filters:
            branches:
              only: 
                - master
