version: 2
jobs:
  build:
    docker:
      - image: docker.io/ncar/nidas-ubuntu-base:latest
    branches:
      only:
        - master
    steps:
      - checkout
      - run: 
        name: NIDAS Build of Master Branch for Host
        command: |
          pwd
          ls -alg
  build-autoconfig-armhf:
    docker:
      - image: docker.io/ncar/nidas:latest
    branches:
      only:
        - auto-config
    steps:
      - checkout
      - run:
        name: NIDAS Build of AutoConfig Branch for RPi DSM
        command: |
          pwd
          cd nidas/src
          scons LINUX_MODULES=no BUILDS=armhf
