version: 2
jobs:
  build-host:
    docker:
      - image: docker.io/ncar/nidas-ubuntu-base:latest
    steps:
      - checkout
      - run:
          name: NIDAS Build of Master Branch for Host
          command: |
            cd src
            scons LINUX_MODULES=no BUILDS=host
  build-rpi-armhf:
    docker:
      - image: docker.io/ncar/nidas:latest
    steps:
      - checkout
      - run:
          name: NIDAS Build of AutoConfig Branch for RPi DSM
          command: | 
            cd src
            scons LINUX_MODULES=no BUILDS=armhf
workflows:
  version: 2
  autoconfig:
    jobs:
      - build-rpi-armhf
  host:
    jobs:
      - build-host