version: 2.1
executors:
  armhf-executor:
    docker:
      - image: docker.io/ncar/nidas-build-debian-armhf:jessie_v1

  armel-executor:
    docker:
      - image: docker.io/ncar/nidas-build-debian-armel:jessie_v1

commands:
  clone-source:
    description: "Clone the source tree"
    steps:
      - run:
          name: Clone GitHub repository
          command: git clone -b ${CIRCLE_BRANCH} --single-branch https://github.com/ncareol/nidas
  
  build:
    description: "Build nidas with arch parameter"
    parameters:
      arch:
        type: string
        default: "host"
    steps:
      - run:
          name: Build NIDAS for << parameters.arch >>
          command: |
            cd nidas/src
            scons LINUX_MODULES=no BUILDS=<< parameters.arch >>

  test:
    description: "Native Build of nidas then test"
    steps:
      - build
      - run:
          name: NIDAS Native Build and Unit Test
          command: |
            cd nidas/src
            scons LINUX_MODULES=no tests

  build-pkgs:
    description: "Build packages associated arch: armhf, armel"
    parameters:
      arch:
        type: string
        default: "armhf"
    steps:
      - run:
          name: NIDAS Package Build for arch parameter
          command: | 
            pushd nidas/scripts
            ./build_dpkg.sh armhf
            popd
            ls -alg
            mkdir pkgs && cp *.deb pkgs
            ls -alg pkgs

  deploy-pkgs:
    description: "Deploy packages to packagecloud.io"
    steps:
      - deploy:
          name: Upload all packages to debian:jessie packagecloud.io
          command: |
             package_cloud push ncareol/isfs/raspbian/jessie ./pkgs/nidas-*_arm*.deb

jobs:
  build-armhf-master:
    executor: armhf-executor
    working_directory: .
    steps:
      - clone-source
      - build:
          arch: armhf

  test-armhf-master:
    executor: armhf-executor
    working_directory: .
    steps:
      - clone-source
      - test

  package-armhf-master:
    executor: armhf-executor
    working_directory: .
    steps:
      - clone-source
      - build-pkgs:
          arch: armhf
      - persist_to_workspace:
          root: .
          paths: pkgs

  deploy-armhf-master:
    executor: armhf-executor
    working_directory: .
    environment:
      PACKAGECLOUD_TOKEN: 06ddd11da1ae900dccd755ce1acd48ee6ab9f62e2d930318
    steps:
      - attach_workspace:
          at: .
      - deploy-pkgs
  
  build-armel-master:
    executor: armel-executor
    working_directory: .
    steps:
      - clone-source
      - build

  test-armel-master:
    executor: armel-executor
    working_directory: .
    steps:
      - clone-source
      - test

  package-armel-master:
    executor: armel-executor
    working_directory: .
    steps:
      - clone-source
      - build-pkgs:
          arch: armel
      - persist_to_workspace:
          root: .
          paths: pkgs

  deploy-armel-master:
    executor: armel-executor
    working_directory: .
    environment:
      PACKAGECLOUD_TOKEN: 06ddd11da1ae900dccd755ce1acd48ee6ab9f62e2d930318
    steps:
      - attach_workspace:
          at: .
      - deploy-pkgs
  
  build-armhf-autoconfig:
    executor: armhf-executor
    working_directory: .
    steps:
      - clone-source
      - build:
          arch: armhf

  test-armhf-autoconfig:
    executor: armhf-executor
    working_directory: .
    steps:
      - clone-source
      - test

  package-armhf-autoconfig:
    executor: armhf-executor
    working_directory: .
    steps:
      - clone-source
      - build-pkgs:
          arch: armhf
      - persist_to_workspace:
          root: .
          paths: pkgs

  deploy-armhf-autoconfig:
    executor: armhf-executor
    environment:
      PACKAGECLOUD_TOKEN: 06ddd11da1ae900dccd755ce1acd48ee6ab9f62e2d930318
    working_directory: .
    steps:
      - attach_workspace:
          at: .
      - deploy-pkgs

  build-armel-autoconfig:
    executor: armel-executor
    working_directory: .
    steps:
      - clone-source
      - build:
          arch: armel

  test-armel-autoconfig:
    executor: armel-executor
    working_directory: .
    steps:
      - clone-source
      - test 

  package-armel-autoconfig:
    executor: armel-executor
    working_directory: .
    steps:
      - clone-source
      - build-pkgs:
          arch: armel
      - persist_to_workspace:
          root: .
          paths: pkgs
    
  deploy-armel-autoconfig:
    executor: armel-executor
    working_directory: .
    environment:
      PACKAGECLOUD_TOKEN: 06ddd11da1ae900dccd755ce1acd48ee6ab9f62e2d930318
    steps:
      - attach_workspace:
          at: .
      - deploy-pkgs

workflows:
  version: 2
  # master-armhf:
  #   jobs:
      # - build-armhf-master:
      #     filters:
      #       branches:
      #         only: 
      #           - master
      # - test-armhf-master:
      #     filters:
      #       branches:
      #         only: 
      #           - master
      # - package-armhf-master:
      #     # requires:
      #     #   - test-armhf-master
      #     filters:
      #       branches:
      #         only: 
      #           - master
      # - deploy-armhf-master:
      #     # requires:
      #     #   - package-armhf-master
      #     filters:
      #       branches:
      #         only: 
      #           - master
      
  # master-armel:
  #   jobs:
      # - build-armel-master:
      #     filters:
      #       branches:
      #         only: 
      #           - master
      # - test-armel-master:
      #     filters:
      #       branches:
      #         only: 
      #           - master
      # - package-armel-master:
      #   #  requires:
      #   #    - test-armel-master
      #     filters:
      #       branches:
      #         only: 
      #           - master
      # - deploy-armel-master:
      #     # requires:
      #     #   - package-armel-master
      #     filters:
      #       branches:
      #         only: 
      #           - master

  autoconfig-armhf:
    jobs:
      # - build-armhf-autoconfig:
      #     filters:
      #       branches:
      #         only: 
      #           - auto-config
      - test-armhf-autoconfig:
          filters:
            branches:
              only: 
                - auto-config
      - package-armhf-autoconfig:
          requires:
            - test-armhf-autoconfig
          filters:
            branches:
              only: 
                - auto-config
      - deploy-armhf-autoconfig:
          requires:
            - package-armhf-autoconfig
          filters:
            branches:
              only: 
                - auto-config
      
  autoconfig-armel:
    jobs:
      # - build-armel-autoconfig:
      #     filters:
      #       branches:
      #         only: 
      #           - auto-config
      - test-armel-autoconfig:
          filters:
            branches:
              only: 
                - auto-config
      - package-armel-autoconfig:
          requires:
            - test-armel-autoconfig
          filters:
            branches:
              only: 
                - auto-config
      - deploy-armel-autoconfig:
          requires:
            - package-armel-autoconfig
          filters:
            branches:
              only: 
                - auto-config
