version: 2.1
executors:
  armhf-executor:
    docker:
      - image: docker.io/ncar/nidas-build-debian-armhf:jessie_v1

  armel-executor:
    docker:
      - image: docker.io/ncar/nidas-build-debian-armel:jessie_v1
 
jobs:
  build-armhf-master:
    executor: armhf-executor
    steps:
      - run:
          name: Clone GitHub repository
          command: git clone -b ${CIRCLE_BRANCH} --single-branch https://github.com/ncareol/nidas
      - run:
          name: NIDAS Build of Master Branch for RPi/armhf
          command: |
            cd nidas/src
            scons LINUX_MODULES=no BUILDS=armhf

  package-armhf-master:
    executor: armhf-executor
    steps:
      - run:
          name: Clone GitHub repository
          command: git clone -b ${CIRCLE_BRANCH} --single-branch https://github.com/ncareol/nidas
      - run:
          name: NIDAS Package Build of Master Branch for RPi/armhf
          command: | 
            cd nidas/scripts
            ./build_dpkg.sh armhf

  deploy-armhf-master:
  
  build-armel-master:
    executor: armel-executor
    steps:
      - run:
          name: Clone GitHub repository
          command: git clone -b ${CIRCLE_BRANCH} --single-branch https://github.com/ncareol/nidas
      - run:
          name: NIDAS Build of Master Branch for PC104/armel
          command: |
            cd nidas/src
            scons LINUX_MODULES=no BUILDS=armel

  package-armel-master:
    executor: armel-executor
    steps:
      - run:
          name: Clone GitHub repository
          command: git clone -b ${CIRCLE_BRANCH} --single-branch https://github.com/ncareol/nidas
      - run:
          name: NIDAS Package Build of Master Branch for PC104/armel
          command: | 
            cd nidas/scripts
            ./build_dpkg.sh armel

  deploy-armel-master:
  
  build-armhf-autoconfig:
    executor: armhf-executor
    steps:
      - run:
          name: Clone GitHub repository
          command: git clone -b ${CIRCLE_BRANCH} --single-branch https://github.com/ncareol/nidas
      - run:
          name: NIDAS Build of AutoConfig Branch for RPi/armhf
          command: | 
            cd nidas/src
            scons LINUX_MODULES=no BUILDS=armhf

  package-armhf-autoconfig:
    executor: armhf-executor
    steps:
      - run:
          name: Clone GitHub repository
          command: git clone -b ${CIRCLE_BRANCH} --single-branch https://github.com/ncareol/nidas
      - run:
          name: NIDAS Package Build of AutoConfig Branch for RPi/armhf
          command: | 
            cd nidas/scripts
            ./build_dpkg.sh armhf

  deploy-armhf-autoconfig:

  build-armel-autoconfig:
    executor: armel-executor
    steps:
      - run:
          name: Clone GitHub repository
          command: git clone -b ${CIRCLE_BRANCH} --single-branch https://github.com/ncareol/nidas
      - run:
          name: NIDAS Build of AutoConfig Branch for PC104/armel
          command: | 
            cd nidas/src
            scons LINUX_MODULES=no BUILDS=armel

  package-armel-autoconfig:
    executor: armhf-executor
    steps:
      - run:
          name: Clone GitHub repository
          command: git clone -b ${CIRCLE_BRANCH} --single-branch https://github.com/ncareol/nidas
      - run:
          name: NIDAS Package Build of AutoConfig Branch for PC104/armel
          command: | 
            cd nidas/scripts
            ./build_dpkg.sh armel
    
  deploy-armel-autoconfig:

workflows:
  version: 2
  master-armhf:
    jobs:
      - build-armhf-master:
          filters:
            branches:
              only: 
                - master
      - package-armhf-master:
          requires:
            - build-armhf-master
          filters:
            branches:
              only: 
                - master
      
  master-armel:
    jobs:
      - build-armel-master:
          filters:
            branches:
              only: 
                - master
      - package-armel-master:
          requires:
            - build-armel-master
          filters:
            branches:
              only: 
                - master

  autoconfig-armhf:
    jobs:
      - build-armhf-autoconfig:
          filters:
            branches:
              only: 
                - auto-config
      - package-armhf-autoconfig:
          requires:
            - build-armhf-autoconfig
          filters:
            branches:
              only: 
                - auto-config
      
  autoconfig-armel:
    jobs:
      - build-armel-autoconfig:
          filters:
            branches:
              only: 
                - auto-config
      - package-armel-autoconfig:
          requires:
            - build-armel-autoconfig
          filters:
            branches:
              only: 
                - auto-config
