#!/bin/sh
##
## Shell script for generating Doxygen documents for the ADS3 code.
##
## Copyright 2005 UCAR, NCAR, All Rights Reserved
##
## $LastChangedDate: 2004-10-15 17:53:32 -0600 (Fri, 15 Oct 2004) $
##
## $LastChangedRevision: 1703 $
##
## $LastChangedBy: wasinger $
##
## $HeadURL: http://orion/svn/hiaper/nids/dsm/doxy/make_doc $
##

nids_dir() {
    echo /scr/tmp/$LOGNAME/nids_doxy
}

svn_co_nids() {
    local dir=`nids_dir`
    [ -d $dir ] && rm -rf $dir
    mkdir -p $dir
    cd $dir
    svn co http://svn/svn/nids/trunk nids
    cd nids
}

atdUtil_dir() {
    echo /scr/tmp/$LOGNAME/atdUtil_doxy
}

cvs_co_atdUtil() {
    local dir=`atdUtil_dir`
    [ -d $dir ] && rm -rf $dir
    mkdir -p $dir
    cd $dir
    cvs -d /code/cvs co -d atdUtil isa/src/lib/atdUtil
    cd atdUtil
}

if true; then
    # DSM
    codir=`nids_dir`/nids
    if [ ! -d $codir ]; then
	svn_co_nids
    else
	cd $codir || exit 1
	svn update || svn_co_nids
    fi

    cd $codir/dsm || exit 1

    doxygen doxy/dsm.doxy

    rsync -a doc /net/www/docs/raf/Software/hiaper/nids/apidocs/dsm
fi

# atdUtil
codir=`atdUtil_dir`/atdUtil
if [ ! -d $codir ]; then
    cvs_co_atdUtil
else
    cd $codir || exit 1
    cvs update || cvs_co_atdUtil
fi

cd $codir || exit 1

doxygen atdUtil.doxy

rsync -a doc /net/www/docs/raf/Software/hiaper/nids/apidocs/atdUtil
