# -*- python -*-

Import('env')
env = env.Clone(tools = ['nidasutil', 'nidas', 'valgrind'])

env.Append(CXXFLAGS='-Wno-effc++')
env.Append(LIBS = env.NidasLibs())
env.Append(LIBS = ['boost_unit_test_framework', 'boost_regex'])
env.Prepend(CPPPATH = [ "#/nidas/util", "#/nidas/core", "#/nidas/dynld" ])
tests = env.Program('tgps', ["tgps.cc"])

env.AppendENVPath('LD_LIBRARY_PATH', '/opt/nc_server/lib')
runtest = env.Command("xtest", tests,
                      env.ChdirActions(["./$SOURCE.file -r detailed -l all "
                                        "--no_color_output"]))
env.Precious(runtest)
AlwaysBuild(runtest)
Alias('test', runtest)

env.ValgrindLog('memcheck', 
                env.Command('vg.memcheck.log', tests,
                            "cd ${SOURCE.dir} && "
                            "${VALGRIND_PATH} --leak-check=full"
                            " --gen-suppressions=all ./${SOURCE.file}"
                            " >& ${TARGET.abspath}"))

env.ValgrindLog('threadcheck', 
                env.Command('vg.threadcheck.log', tests,
                            "cd ${SOURCE.dir} && "
                            "${VALGRIND_PATH} --tool=helgrind"
                            " --gen-suppressions=all ./${SOURCE.file}"
                            " >& ${TARGET.abspath}"))

