# -*- python -*-
# 2009, Copyright University Corporation for Atmospheric Research

from SCons.Script import Environment

env = Environment(tools=['default', 'nidasapps'])

ck_xml = env.NidasApp('ck_xml')
datasets = env.NidasApp('datasets')

depends = ["run_test.sh", ck_xml, datasets]
runtest = env.Command("xtest1", depends,
                      ["cd $SOURCE.dir && ./run_test.sh --valgrind"])

env.Precious(runtest)
env.AlwaysBuild(runtest)
env.Alias('test', runtest)
env.Alias('ck_xml_test', runtest)
