# -*- python -*-

Import('env')
env = env.Clone()
env.Require('nidas')

ck_xml = env.NidasApp('ck_xml')

depends = ["run_test.sh",ck_xml]
runtest = env.Command("xtest1", depends, ["cd $SOURCE.dir && ./run_test.sh"])

env.Precious(runtest)
env.AlwaysBuild(runtest)
env.Alias('test', runtest)
env.Alias('ck_xml_test', runtest)
