# -*- python -*-
## 2010, Copyright University Corporation for Atmospheric Research

from SCons.Script import Environment, Import

##
##  Import the build environment.
##
Import(['env'])

env: Environment

env.NidasKernelModule(['lamsx.ko'],
    ['lamsx.c', *env.SymbolModules('revinfo', 'util')],
    ['lamsx.h'])
