# -*- python -*-
## 2010, Copyright University Corporation for Atmospheric Research


##
##  Import the build environment.
##
Import(['env', 'first_mach'])
mach = env['MACH']

# The Makefile must be listed in the source dependencies
# so that it is copied/linked to the variant_dir.
# The Kmake builder runs the make command in variant_dir.
#
# Also, the SConscript command that invokes this SConscript
# file should set duplicate=1, so that all the linux module
# source files, including the Makefile, are copied to the variant_dir.
# so that make can find them and do its work outside of the
# source tree.

# All modules must be built by the same kmake builder so SCons will setup
# all the variant_dir copies/links before running make.  Otherwise make
# fails because not all the dependencies exist yet.

if env.get("LINUX_MODULES_INST_PATH") and env.get("KERNELDIR"):

    revinfo = Dir('./../../include/nidas/linux').File('Revision.h')
    utilsyms = Dir('./../util_' + mach).File('Module.symvers')

    modules = ['lamsx.ko']
    env.Kmake(modules,
              ['lamsx.c', 'lamsx.h', 'Makefile', revinfo, utilsyms])

    env.Install('$LINUX_MODULES_INST_PATH',modules)

    env.Clean('install',[
        '$LINUX_MODULES_INST_PATH/' + l for l in modules
        ])

# Some kernel module header files define symbols that are needed
# by user code. These must also be installed in $ARCHPREFIX/include
headers = Split("""
    lamsx.h
""")

if first_mach:
    env.Install('$ARCHPREFIX/include/nidas/linux/lams',headers)
