# -*- python -*-
## 2007, Copyright University Corporation for Atmospheric Research

from SCons.Script import Environment, Import

##
##  Import the build environment.
##
Import(['env'])

env: Environment

env.NidasKernelModule(
    ['ncar_a2d.ko'],
    ['ncar_a2d.c', "ncar_a2d_priv.h"] +
    env.SymbolModules('revinfo', 'util', 'filters', 'irig')
)
