# -*- python -*-
## 2007, Copyright University Corporation for Atmospheric Research


##
##  Import the build environment.
##
Import(['env', 'first_mach'])
mach = env['MACH']

# The Makefile must be listed in the source dependencies
# so that it is copied/linked to the variant_dir.
# The Kmake builder runs the make command in variant_dir.
#
# Also, the SConscript command that invokes this SConscript
# file should set duplicate=1, so that all the linux module
# source files, including the Makefile, are copied to the variant_dir.
# so that make can find them and do its work outside of the
# source tree.

#
headers = Split("""
ncar_a2d_priv.h
""")

if env.has_key("LINUX_MODULES_INST_PATH") and \
    env.has_key('KERNELDIR') and env['KERNELDIR'] != '':

    revinfo = Dir('./../../include/nidas/linux').File('Revision.h')
    utilsyms = Dir('./../util_' + mach).File('Module.symvers')
    filtsyms = Dir('./../filters_' + mach).File('Module.symvers')
    irigsyms = Dir('./../irig_' + mach).File('Module.symvers')

# print("symvers=%s" % symvers)

    modules = ['ncar_a2d.ko']

    env.Kmake(modules, headers + ['ncar_a2d.c', 'Makefile', revinfo, utilsyms, filtsyms, irigsyms])

    env.Install('$LINUX_MODULES_INST_PATH', modules)

    env.Clean('install',[
        '$LINUX_MODULES_INST_PATH/' + l for l in modules
        ])

# Some kernel module header files define symbols that are needed
# by user code. These must also be installed in $ARCHPREFIX/include
shared_headers = Split("""
""")

env.Install('$ARCHPREFIX/include/nidas/linux/ncar_a2d', shared_headers)
