# -*- python -*-

Import('env')
env = env.Clone()

# Set LD_LIBRARY_PATH to the locally build libraries.

# 07/28/2010: env.GetGlobalTarget is not finding these names
# libs = [ env.GetGlobalTarget(name) for name in
#          ['libnidas', 'libnidas_util', 'libnidas_dynld'] ]
libs = [env['LIBNIDAS_UTIL'], env['LIBNIDAS'], env['LIBNIDAS_DYNLD']]

ldlibdirs = [ l.Dir('').abspath for l in env.File(libs) ]

env['ENV']['LD_LIBRARY_PATH'] = ":".join(ldlibdirs)

env.Prepend( LIBS= libs, LIBPATH=ldlibdirs)
env.Prepend(CPPPATH = [ '#/src' ])
env.Append(CCFLAGS = ['-Wall'])

tests = env.Program('dns_lookup', "dns_lookup.cc")

runtest = env.Command("dns_test", tests, ["$SOURCE.abspath"])
env.Precious(runtest)
AlwaysBuild(runtest)
Alias('test', runtest)

