# -*- python -*-
## 2009, Copyright University Corporation for Atmospheric Research

Import('env')
env = env.Clone(tools = ['nidas'])

env.Append(LIBS = env.NidasUtilLibs())
env.Prepend(CPPPATH = [ '#/src' ])
env.Append(CCFLAGS = ['-Wall'])

tests = env.Program('dns_lookup', "dns_lookup.cc")

runtest = env.Command("dns_test", tests, ["$SOURCE.abspath"])
env.Precious(runtest)
AlwaysBuild(runtest)
Alias('networktest', runtest)
Alias('test', runtest)

