# -*- python -*-
##  Copyright 2005,2006 UCAR, NCAR, All Rights Reserved

Import('env')
arch = env['ARCH']  # empty string for native builds

sources = Split("""
    A2DBoardTempSensor.cc
    ADC_HW_EB7022597.cc
    Aircraft.cc
    Arinc_IRS.cc
    CDP_Serial.cc
    CMIGITS3_Serial.cc
    CVI_LV_Input.cc
    CVIOutput.cc
    CVIProcessor.cc
    DSMAnalogSensor.cc
    DSMArincSensor.cc
    LamsSensor.cc
    LamsNetSensor.cc
    DSMMesaSensor.cc
    GPS_HW_HG2021GB02.cc
    IRIGSensor.cc
    IRS_HW_HG2001GD.cc
    IRS_HW_YG1854.cc
    LSZ_HW_EB7032239.cc
    PPT_Serial.cc
    PSI9116_Sensor.cc
    SidsNetSensor.cc
    SppSerial.cc
    SPP100_Serial.cc
    SPP200_Serial.cc
    SPP300_Serial.cc
    SyncRecordGenerator.cc
    SyncRecordReader.cc
    SyncRecordSource.cc
    SyncServer.cc
    Twins.cc
    TwoD_House.cc
    TwoD_USB.cc
    TwoD64_USB.cc
    TwoD32_USB.cc
    UDPSocketSensor.cc
    UHSAS_Serial.cc
    VCSEL_Serial.cc
    VCSEL2_Serial.cc
""")


headers = Split("""
    A2DBoardTempSensor.h
    ADC_HW_EB7022597.h
    Aircraft.h
    Arinc_IRS.h
    CDP_Serial.h
    CMIGITS3_Serial.h
    CVI_LV_Input.h
    CVIOutput.h
    CVIProcessor.h
    DSMAnalogSensor.h
    DSMArincSensor.h
    LamsSensor.h
    LamsNetSensor.h
    DSMMesaSensor.h
    GPS_HW_HG2021GB02.h
    IRIGSensor.h
    IRS_HW_HG2001GD.h
    IRS_HW_YG1854.h
    LSZ_HW_EB7032239.h
    PPT_Serial.h
    PSI9116_Sensor.h
    SidsNetSensor.h
    SppSerial.h
    SPP100_Serial.h
    SPP200_Serial.h
    SPP300_Serial.h
    SyncRecordGenerator.h
    SyncRecordReader.h
    SyncRecordSource.h
    SyncRecordVariable.h
    SyncServer.h
    Twins.h
    TwoD_House.h
    TwoD_USB.h
    TwoD64_USB.h
    TwoD32_USB.h
    UHSAS_Serial.h
    UDPSocketSensor.h
    VCSEL_Serial.h
    VCSEL2_Serial.h
""")

if arch == 'arm':
    archsources=Split("""
    """)
    archheaders=Split("""
    """)
else:
    archsources=Split("""
    """)
    archheaders=Split("""
    """)


env.Append (LIBNIDAS_DYNLD_SOURCES = [ env.File(f) for f in sources + archsources ])

if arch == '':
    env.Install('$PREFIX/include/nidas/dynld/raf', headers + archheaders)
