# -*- python -*-

Import('env')
env = env.Clone()

libs = [ env['LIBNIDAS_DYNLD'], env['LIBNIDAS'], env['LIBNIDAS_UTIL'] ]
env.Append(
    LIBS= [ env.subst("${TARGET.file}", target=l) for l in libs ],
    LIBPATH=[ l.Dir('') for l in env.File(libs) ])
env.Append(LIBS = ['boost_unit_test_framework', 'boost_regex'])
env.Append(CPPPATH = [ "#" ])
env.Append(CCFLAGS = ['-Wall'])

tests = env.Program('tiostream', "tiostream.cc")
# env.Depends(tests, libs)

ldlibdirs = [ l.Dir('').abspath for l in env.File(libs) ]
env['ENV']['LD_LIBRARY_PATH'] = ":".join(ldlibdirs)
# print 'LD_LIBRARY_PATH=' + env['ENV']['LD_LIBRARY_PATH']

# Add --log_level=all to see all the log messages
runtest = env.Command("xtest", tests, ["$SOURCE.abspath"])
env.Precious(runtest)
AlwaysBuild(runtest)
Alias('test', runtest)



