# -*- python -*-
## 2007, Copyright University Corporation for Atmospheric Research

from SCons.Script import Environment, Import

##
##  Import the build environment.
##
Import(['env'])

env: Environment

env.NidasKernelModule(
    ['nidas_util.ko'],
    ['nidas_util.c', *env.SymbolModules('revinfo')])
