# -*- python -*-

##
##  Import the server-build environment.
##
Import('x86_env')
src_x86_env = x86_env.Copy()

##
##  List the x86 specific libraries
##
src_x86_env['LIBS'] = Split("""
  libX86Disc.a
""")

##
##  Build discAsync, discSync, discComm
##
#  main.cc
apps = Split("""
""")

for i in apps:
  src_x86_env.Program( i )
