# -*- python -*-

##  Copyright 2005 UCAR, NCAR, All Rights Reserved

##
##  Import the server-build environment.
##
Import('env')

myenv = env.Copy()

##
##  Build discAsync, discSync, discComm
##
#  main.cc
apps = Split("""
""")

for i in apps:
  myenv.Program( i )
