
from SCons.Script import Environment, Import

Import('env')
env: Environment

scripts = env.Split("cktty irout irqs vout")

# Install start_podman everywhere even though it's not likely to be useful
# except on redhat systems, time and necessity to do otherwise are lacking.
# Likewise for other utility scripts like irout and vout.  It's just not worth
# it at the moment to specialize them.

env.Install("$PREFIX/bin", "setup_nidas.sh")
env.Install("$PREFIX/bin", "start_podman")
env.Install("$PREFIX/bin", scripts)

env.Alias('install', ['${INSTALL_ROOT}$PREFIX/bin'])
