# -*- python -*-

##  Copyright 2005,2006 UCAR, NCAR, All Rights Reserved

##
##  Import the build environment.
##
Import('env')
arch = env['ARCH']

subdirs=Split("""emerald""")

##
## ARCH target for creating modules, library, and executables
##
env.Alias(arch, ['build_%s' % dir for dir in subdirs ])

# Provide an arch-specific install alias.  Basically, install everything
# that goes under the arch-specific install prefix.
archinstall= env.Alias(arch+'_install', [ '$PREFIX' ])

for dir in subdirs:
    SConscript('%s/SConscript' % dir,
               build_dir='build_%s' % dir,
               duplicate=1,exports={'env':env})

Default([ "build_%s" % dir for dir in subdirs ])
