/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "nc_server_rpc.h"

bool_t
xdr_NS_rectype(register XDR *xdrs, NS_rectype *objp)
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_NS_datatype(register XDR *xdrs, NS_datatype *objp)
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_NSlong(register XDR *xdrs, NSlong *objp)
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_int(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_field(register XDR *xdrs, field *objp)
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_string(xdrs, &objp->name, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->units, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_dimension(register XDR *xdrs, dimension *objp)
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_string(xdrs, &objp->name, ~0))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->size))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_str_attr(register XDR *xdrs, str_attr *objp)
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_string(xdrs, &objp->name, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->value, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_str_attrs(register XDR *xdrs, str_attrs *objp)
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_array(xdrs, (char **)&objp->attrs.attrs_val, (u_int *) &objp->attrs.attrs_len, ~0,
		sizeof (str_attr), (xdrproc_t) xdr_str_attr))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_datadef(register XDR *xdrs, datadef *objp)
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_double(xdrs, &objp->interval))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->connectionId))
		return (FALSE);
	if (!xdr_NS_rectype(xdrs, &objp->rectype))
		return (FALSE);
	if (!xdr_NS_datatype(xdrs, &objp->datatype))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->fields.fields_val, (u_int *) &objp->fields.fields_len, ~0,
		sizeof (field), (xdrproc_t) xdr_field))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->dimensions.dimensions_val, (u_int *) &objp->dimensions.dimensions_len, ~0,
		sizeof (dimension), (xdrproc_t) xdr_dimension))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->attrs.attrs_val, (u_int *) &objp->attrs.attrs_len, ~0,
		sizeof (str_attrs), (xdrproc_t) xdr_str_attrs))
		return (FALSE);
	if (!xdr_float(xdrs, &objp->floatFill))
		return (FALSE);
	if (!xdr_NSlong(xdrs, &objp->longFill))
		return (FALSE);
	if (!xdr_bool(xdrs, &objp->fillmissingrecords))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_datarec_float(register XDR *xdrs, datarec_float *objp)
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_double(xdrs, &objp->time))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->connectionId))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->datarecId))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->cnts.cnts_val, (u_int *) &objp->cnts.cnts_len, ~0,
		sizeof (NSlong), (xdrproc_t) xdr_NSlong))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->start.start_val, (u_int *) &objp->start.start_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->count.count_val, (u_int *) &objp->count.count_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_datarec_long(register XDR *xdrs, datarec_long *objp)
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_double(xdrs, &objp->time))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0,
		sizeof (NSlong), (xdrproc_t) xdr_NSlong))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->connectionId))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->datarecId))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->cnts.cnts_val, (u_int *) &objp->cnts.cnts_len, ~0,
		sizeof (NSlong), (xdrproc_t) xdr_NSlong))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->start.start_val, (u_int *) &objp->start.start_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->count.count_val, (u_int *) &objp->count.count_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_historyrec(register XDR *xdrs, historyrec *objp)
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_string(xdrs, &objp->history, ~0))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->connectionId))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_connection(register XDR *xdrs, connection *objp)
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_double(xdrs, &objp->filelength))
		return (FALSE);
	if (!xdr_double(xdrs, &objp->interval))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->filenamefmt, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->outputdir, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->cdlfile, ~0))
		return (FALSE);
	return (TRUE);
}
