# -*- python -*-

##
##  Import the cross-build environment.
##

Import('env')
myenv = env.Copy()

##
##  List the source files compiled into the libDsm.a library.
##
#  Climet.cc
#  Dpres.cc
#  Neph.cc
#  SampleTable.cc
#  SerialTable.cc
#  SyncRecord.cc

sources = Split("""
  DSMEngine.cc
  DSMSensor.cc
  RTL_DevIoctl.cc
  RTL_DevIoctlStore.cc
  RTL_DSMSensor.cc
  DSMSerialSensor.cc
  Sample.cc
  SampleClientList.cc
  SampleSourceImpl.cc
  PortSelector.cc
  PortSelectorTest.cc
  RemoteSerialConnection.cc
  RemoteSerialListener.cc
  TestSampleClient.cc
  AsciiScanner.cc
  DOMObjectFactory.cc
  DynamicLoader.cc
  DOMable.cc
  DSMConfig.cc
  Aircraft.cc
  Project.cc
  SensorCatalog.cc
  XMLParser.cc
  XMLConfigWriter.cc
  XMLFdFormatTarget.cc
  XMLConfigService.cc
  ConfigRequestor.cc
  IRIGSensor.cc
  DSMServer.cc
  OutputStream.cc
  InputStream.cc
  SampleInputStream.cc
  SampleOutputStream.cc
  DSMService.cc
  RawSampleService.cc
  SyncRecordService.cc
  SocketAddress.cc
  DSMInputFileSet.cc
  DSMOutputFileSet.cc
  SampleSorter.cc
  RawSampleOutput.cc
  RawSampleServiceRequestor.cc
  SyncRecordServiceRequestor.cc
  SyncRecordOutput.cc
  Variable.cc
  SampleTag.cc
""")

## myenv['LEXCOM'] = '$LEX $LEXFLAGS -t $SOURCES > $TARGET'

## myenv['LEXFLAGS'] = Split("""
##     -Pscanf_fmt_yy -+
## """)

myenv.CXXFile(target='AsciiScanner.cc',source='AsciiScanner.ll')

##
##  Build the libArmDsm.a library.
##
## myenv.StaticLibrary('Dsm' , sources)
myenv.SharedLibrary('Dsm' , sources)
