# -*- python -*-

##
##  Import the cross-build environment.
##

Import('env')
myenv = env.Copy()

##
##  List the source files compiled into the libDsm.a library.
##
# DSMArincSensor.cc
#  SocketAddress.cc
#  RawSampleServiceRequestor.cc
#  SyncRecordServiceRequestor.cc

sources = Split("""

  Project.cc
  Aircraft.cc
  DSMConfig.cc
  SensorCatalog.cc

  DSMEngine.cc
  DSMServer.cc

  DSMSensor.cc
  RTL_DevIoctl.cc
  RTL_DevIoctlStore.cc
  RTL_DSMSensor.cc

  DSMSerialSensor.cc
  AsciiScanner.cc
  IRIGSensor.cc

  Sample.cc
  Variable.cc
  SampleTag.cc

  SampleClientList.cc
  SampleSourceImpl.cc

  PortSelector.cc
  PortSelectorTest.cc
  RemoteSerialConnection.cc
  RemoteSerialListener.cc

  DOMObjectFactory.cc
  DynamicLoader.cc
  DOMable.cc

  XMLParser.cc
  XMLConfigWriter.cc
  XMLFdFormatTarget.cc

  DSMService.cc
  XMLConfigService.cc
  RawSampleService.cc

  Input.cc
  Output.cc
  InputStream.cc
  OutputStream.cc
  McSocketAccepterInput.cc
  McSocketRequesterInput.cc
  McSocketAccepterOutput.cc
  McSocketRequesterOutput.cc
  FileSetInput.cc
  FileSetOutput.cc

  SampleInput.cc
  SampleOutput.cc
  RawSampleOutputStream.cc
  RawSampleInputStream.cc
  SyncRecordOutput.cc

  SampleSorter.cc
  SyncRecordGenerator.cc

""")

## myenv['LEXCOM'] = '$LEX $LEXFLAGS -t $SOURCES > $TARGET'

## myenv['LEXFLAGS'] = Split("""
##     -Pscanf_fmt_yy -+
## """)

myenv.CXXFile(target='AsciiScanner.cc',source='AsciiScanner.ll')

##
##  Build the libArmDsm.a library.
##
## myenv.StaticLibrary('Dsm' , sources)
myenv.SharedLibrary('Dsm' , sources)
