# -*- python -*-

Import('env')
env = env.Clone()

# Set LD_LIBRARY_PATH to the locally build libraries.
#
# 07/28/2010: env.GetGlobalTarget is not finding these names
# libs = env.GetGlobalTarget('libnidas_util')
libs = [env['LIBNIDAS_UTIL']]

ldlibdirs = [ l.Dir('').abspath for l in env.File(libs) ]

env['ENV']['LD_LIBRARY_PATH'] = ":".join(ldlibdirs)

env['LIBS']= [libs,'pthread']
env['LIBPATH']=ldlibdirs
env.Prepend(CPPPATH = [ '#/src' ])
env.Append(CCFLAGS = ['-Wall'])

tests = env.Program('ck_utime', "ck_utime.cc")


runtest = env.Command("ck_ut",[tests,"run_test.sh"],["cd ${SOURCE.dir} && ./run_test.sh"])
env.Precious(runtest)
AlwaysBuild(runtest)
Alias('ck_utime', runtest)
Alias('test', runtest)

