# -*- python -*-
# 2010, Copyright University Corporation for Atmospheric Research

from SCons.Script import Environment

env = Environment(tools=['default', 'nidasapps', 'valgrind', 'boost_test'])

tests = env.Program('ck_utime', "ck_utime.cc")
utime = env.NidasApp('utime')

runtest = env.Command("xtest", [tests, utime, "run_test.sh"],
                      ["cd ${SOURCE.dir} && ./run_test.sh"])
env.Precious(runtest)
env.AlwaysBuild(runtest)
env.Alias('ck_utime', runtest)
env.Alias('test', runtest)
