# -*- python -*-

Import('env')
myenv = env.Copy()

##
##  List the source files for the libArmDisc.a library...
##
##  Note that the source files used to build this library is a
##  subset of those used to build libX86Disc.a.
##
sources = Split("""
  portable.cc
  DsmConfig.cc
  RandomBuf.cc
  TapeHeader.cc
  VarConfig.cc
""")


##
##  Build both libraries.
##
myenv.StaticLibrary('Disc' , sources)
