# -*- python -*-
## 2007, Copyright University Corporation for Atmospheric Research

from SCons.Script import Import, Environment

##
##  Import the build environment.
##
Import(['env'])

env: Environment

env.NidasKernelModule(
    ['pc104sg.ko'],
    ['pc104sg.c', "pc104sg.h", *env.SymbolModules('revinfo', 'util')])
