# -*- python -*-

##  Copyright 2005 UCAR, NCAR, All Rights Reserved

import glob
import fnmatch
import os

##
##  Import and clone the cross-build environment.
##
Import('env')
env = env.Clone()
arch = env['ARCH']

# env.AppendUnique(CXXFLAGS = Split("""
# """))

##
##  List of headers files
##
headers = [ Split("""
    BitArray.h
    BluetoothAddress.h
    BluetoothRFCommSocket.h
    BluetoothRFCommSocketAddress.h
    Bzip2FileSet.h
    DatagramPacket.h
    EndianConverter.h
    EOFException.h
    Exception.h
    FileSet.h
    Inet4Address.h
    Inet4NetworkInterface.h
    Inet4PacketInfo.h
    Inet4SocketAddress.h
    InterruptedException.h
    InvalidParameterException.h
    IOException.h
    IOTimeoutException.h
    Logger.h
    McSocket.h
    ParseException.h
    Process.h
    SerialOptions.h
    SerialPort.h
    SocketAddress.h
    Socket.h
    Termios.h
    Thread.h
    ThreadSupport.h
    time_constants.h
    UnixSocketAddress.h
    UnknownHostException.h
    UTime.h
    util.h
    """)
]
# print(["headers="] + [str(h) for h in headers])

sources = [ Split("""
    BitArray.cc
    BluetoothAddress.cc
    BluetoothRFCommSocket.cc
    BluetoothRFCommSocketAddress.cc
    Bzip2FileSet.cc
    EndianConverter.cc
    Exception.cc
    FileSet.cc
    Inet4Address.cc
    Inet4SocketAddress.cc
    Logger.cc
    McSocket.cc
    Process.cc
    SerialOptions.cc
    SerialPort.cc
    Socket.cc
    Termios.cc
    Thread.cc
    ThreadSupport.cc
    UnixSocketAddress.cc
    UTime.cc
    util.cc
    """)
]
# print(["sources="] + [str(h) for h in sources])

objects = env.SharedObject(sources)

##
##  Build the libnidas_util library.
##
conf = Configure(env)
if conf.CheckLib('cap'):
    conf.env.AppendUnique(LIBS = 'cap')
if conf.CheckLib('bz2'):
    conf.env.AppendUnique(LIBS = 'bz2')
if conf.CheckLib('bluetooth'):
    conf.env.AppendUnique(LIBS = 'bluetooth')
env = conf.Finish()

# build libnidas_util.so
lib = env.SharedLibrary3('nidas_util' , objects,
    LIBS= ['pthread'] + env['LIBS'])

# Test SConscripts need the full path to the library to set LD_LIBRARY_PATH
Export({'LIBNIDAS_UTIL': lib[0]})

slib = env.StaticLibrary('nidas_util' , objects)

##
## Install targets for libraries and headers.
##
nodes = []
nodes += env.SharedLibrary3Install('$PREFIX',lib)
nodes += env.Install('$PREFIX' + '/' + env['ARCHLIBDIR'],slib)
nodes += env.Install('$PREFIX/include/nidas/util',headers)
Alias('install',nodes)

# env.Clean(arch + '_install', nodes)
env.Clean('install', nodes)
