# -*- python -*-

Import('env')
env = env.Clone()

libs = [env.GetGlobalTarget('LIBNIDAS_UTIL')]

ldlibdirs = [ l.Dir('').abspath for l in env.File(libs) ]

env['ENV']['LD_LIBRARY_PATH'] = ":".join(ldlibdirs)

env.Prepend( LIBS=libs, LIBPATH=ldlibdirs)

env.Append (LIBS = ['boost_unit_test_framework', 'boost_regex'])
env.Prepend(CPPPATH = [ "#/nidas/util" ])
tests = env.Program('tlogger', "tlogger.cc")
# env.Depends(tests, libs)
#

runtest = env.Command("xtest", tests, ["$SOURCE.abspath"])
env.Precious(runtest)
AlwaysBuild(runtest)
Alias('test', runtest)




