# -*- python -*-
## 2007, Copyright University Corporation for Atmospheric Research

Import('env')
env = env.Clone(tools = ['nidas'])

env.Append(LIBS = env.NidasUtilLibs())
env.Append(LIBS = ['boost_unit_test_framework', 'boost_regex'])
env.Prepend(CPPPATH = [ "#/nidas/util" ])
tests = env.Program('tlogger', "tlogger.cc")

runtest = env.Command("xtest", tests, ["$SOURCE.abspath"])
env.Precious(runtest)
AlwaysBuild(runtest)
Alias('test', runtest)




