# -*- python -*-

##
##  Import the cross-build environment.
##

# -D__cpluscplus   -fno-common  -fno-builtin
Import('arm_env')
src_arm_env = arm_env.Copy()

##
##  List the ARM specific libraries
##
src_arm_env['LIBS'] = Split("""
  libArmDsm.a
  libArmDisc.a
""")

##
##  Build dsmAsync, dsmSync, dsmComm
##
# ckrtl_com8.cc
apps = Split("""
  dsmSync.cc
  ck_main.cc
""")

for i in apps:
  src_arm_env.Program( i )
