# -*- python -*-
## 2004, Copyright University Corporation for Atmospheric Research


##
##  Import the cross-build environment.
##
Import('env')
arch = env['ARCH']  # empty string for native builds

if env.has_key('PSQL_ENABLE') and env['PSQL_ENABLE']:

    myenv = env.Clone()

    ##
    ## Look for PostgreSQL library.
    ## It looks like this check needs to be at the top of this file,
    ## just after the env.Copy(), otherwise it hangs forever.
    ##
    conf = Configure(myenv)
    has_psql = conf.CheckLibWithHeader('pq','libpq-fe.h','c',
                                       'PQconnectdb("");')
    myenv = conf.Finish()

    if has_psql:
        print("PSQL shared library enabled.")
        sources = Split("""PSQLChannel.cc PSQLSampleOutput.cc""")
        headers = Split("""PSQLChannel.h PSQLSampleOutput.h""")
        so = myenv.SharedLibrary("nidas_dynld_psql", sources)
        myenv.Install('$PREFIX/lib', so)

        env.Clean('install',[
            ('$PREFIX/lib/' + os.path.basename(File(l).path) for l in so)
        ])

        myenv.Install('$PREFIX/include/nidas/dynld/psql', headers)

