# -*- python -*-
## 2004, Copyright University Corporation for Atmospheric Research

import os
from SCons.Script import Import, Environment, Configure, Split

##
##  Import the cross-build environment.
##
Import('env')
arch = env['ARCH']  # empty string for native builds

if env.get('PSQL_ENABLE'):

    myenv = env.Clone()
    conf = Configure(myenv)
    has_psql = conf.CheckLibWithHeader('pq','libpq-fe.h','c',
                                       'PQconnectdb("");')
    myenv = conf.Finish()

    if has_psql:
        print("PSQL shared library enabled.")
        sources = Split("""PSQLChannel.cc PSQLSampleOutput.cc""")
        headers = Split("""PSQLChannel.h PSQLSampleOutput.h""")
        so = myenv.SharedLibrary("nidas_dynld_psql", sources)
        myenv.Install('$ARCHPREFIX/lib', so)

        env.Clean('install',[
            ('$ARCHPREFIX/lib/' + os.path.basename(env.File(l).path) for l in so)
        ])

        myenv.Install('$ARCHPREFIX/include/nidas/dynld/psql', headers)

