# -*- python -*-

from SCons.Script import Environment

env = Environment(tools=['default', 'nidasapps', 'valgrind'])

prep = env.NidasApp('prep')

env['ENV'].update({'ISFF': env.Dir('config').abspath,
                   'PROJECT': 'TREX',
                   'TREX_CONFIG': 'trex',
                   'CSAT3_SHADOW_FACTOR': '0.16',
                   'RAWDATADIR': env.Dir('data').abspath})

env['VALGRIND_OPTIONS'] = str("--leak-check=full"
                              " --show-leak-kinds=definite,possible"
                              " --errors-for-leak-kinds=definite"
                              " -v --leak-check=full --show-leak-kinds=all"
                              " --gen-suppressions=all")

trextest = env.Valgrind(['output/trex-prep.txt'], [prep],
                        "cd ${TARGET.dir} && "
                        "${VALGRIND_COMMAND} ${SOURCE.file} "
                        "-D 'u.5m#1,v.5m#2,w.5m#3' "
                        "-B '2006 mar 31 00:00:00.05' "
                        "-E '2006 apr 02 23:59' "
                        " > ${TARGET.file}",
                        VALGRIND_DEFAULT='on')
env.AlwaysBuild(trextest)

trexdiff = env.Diff(['baseline/trex-prep.txt', 'output/trex-prep.txt'])

env.Alias('trex-prep-test', [trextest, trexdiff])

env = env.Clone()
env['ENV'].update({'ISFS': env.Dir('config').abspath,
                   'PROJECT': 'SOS'})

sosdata = env.File("data/SOS/isfs_x_20230315_000000.dat.bz2")
sostest = env.Valgrind(['output/sos-prep.txt'], [prep, sosdata],
                       "cd ${TARGET.dir} && "
                       "${VALGRIND_COMMAND} ${SOURCE.file} "
                       "-r 1 "
                       "-D SF_min.1m.ue,SF_min.2m.ue "
                       "-D u.10m.d,P.10m.d,Tsnow.1.2m.d "
                       "${SOURCES[1].abspath}"
                       " > ${TARGET.file}",
                       VALGRIND_DEFAULT='on')
env.AlwaysBuild(sostest)
sosdiff = env.Diff(['baseline/sos-prep.txt', 'output/sos-prep.txt'])
env.Alias('sos-prep-test', [sostest, sosdiff])

env.Alias('test', ["trex-prep-test", "sos-prep-test"])
