# -*- python -*-

Import('env')
env = env.Clone()
env.Require('nidas')
env.Require('valgrind')

prep = env.NidasApp('prep')

env['PREPFLAGS'] = str('-D "u.5m#1,v.5m#2,w.5m#3" '
                       '-B "2006 mar 31 00:00:00.05" '
                       '-E "2006 apr 02 23:59"')

env['ENV'].update({'ISFF': env.Dir('config').abspath,
                   'PROJECT': 'TREX',
                   'TREX_CONFIG': 'trex',
                   'RAWDATADIR': env.Dir('data').abspath})

env['VALGRIND_OPTIONS'] = str("--leak-check=full"
                              " --show-leak-kinds=definite,possible"
                              " --errors-for-leak-kinds=definite"
                              " -v --leak-check=full --show-leak-kinds=all"
                              " --gen-suppressions=all")

preptest = env.Valgrind(['preptest.out'], [prep],
                        "cd ${TARGET.dir} && "
                        "${VALGRIND_COMMAND} ${SOURCE.file} ${PREPFLAGS} "
                        " > preptest.out",
                        VALGRIND_DEFAULT='on')

difftest = env.Diff(['preptest.out', 'preptest.baseline'])

env.AlwaysBuild(preptest)
env.Alias('test', [preptest, difftest])
env.Alias('preptest', [preptest, difftest])
