# -*- python -*-

Import('env')

SConscript('src/SConstruct', exports={'env':env})

bdirs = [ 'dynld', 'core', 'util' ]
ldlibdirs = [ env.Dir('#/build_x86/build_%s' % d).abspath for d in bdirs ]
env['ENV']['LD_LIBRARY_PATH'] = ":".join(ldlibdirs)
path = env.subst("${TARGET.dir}", target=env['NIDAS_APPS']['dsm'])
env.PrependENVPath('PATH', path)

runtest = env.Command("xtest", "run_test.sh",
                      ["cd $SOURCE.dir && ./run_test.sh"])
env.Precious(runtest)
AlwaysBuild(runtest)
Alias('test', runtest)
