#!/bin/sh

script=$0
dir=${script%/*}

export LD_LIBRARY_PATH=$dir/build/build_util:$dir/build/build_core:$dir/build/build_dynld

PATH=$dir/build/build_apps:$dir/build/build_apps/isff:$PATH

app=$1
shift

[ -x $dir/build/build_apps/$app ] && ldd $dir/build/build_apps/$app
[ -x $dir/build/build_apps/isff/$app ] && ldd $dir/build/build_apps/isff/$app

valgrind --leak-check=full $app "$@"
# $app "$@"

