#!/bin/sh

# Run a nidas binary from the build tree

script=$0
dir=${script%/*}

[ -f /etc/os-release ] && . /etc/os-release
variant_dir=build_$(uname -m)_${ID}${VERSION_ID}

export LD_LIBRARY_PATH=$dir/$variant_dir/lib
echo LD_LIBRARY_PATH=$LD_LIBRARY_PATH

PATH=$dir/$variant_dir/bin:$PATH
echo PATH=$dir/$variant_dir/bin:\$PATH

usage() {
    echo "$0 [-v] [-V] app args
    -v: run with valgrind
    -V: run with valgrind --leak-check=full
    app args: nidas app and arguments"
    exit 1
}

[ $# -lt 1 ] && usage

valg=false

case $1 in
-v)
    valg=true
    shift
    [ $# -lt 1 ] && usage
    app=$1
    ;;
-V)
    valg=true
    valargs=--leak-check=full
    shift
    [ $# -lt 1 ] && usage
    app=$1
    ;;
*)
    app=$1
    ;;
esac

shift

# Display the shared libraries so user can be certain the ones 
# in the build directory are being used.
[ -x $dir/$variant_dir/bin/$app ] && ldd $dir/$variant_dir/bin/$app

if $valg; then
    valgrind $valargs $app "$@"
else
    nice $app "$@"
fi

