# -*- python -*-
## 2007, Copyright University Corporation for Atmospheric Research

from SCons.Script import Environment, Import

Import(['env'])
env: Environment
mach = env['MACH']

if mach == 'viper':
    env.NidasKernelModule(
        ['viper_dio.ko'],
        ['viper_dio.c', *env.SymbolModules('revinfo')],
        'viper_dio.h')

# Technically this is not quite equivalent to the previous setup, where the
# header was installed even when the module build was disabled and the target
# machine was not a viper.  That seems unlikely to be needed at this point.
